### ISSUE TITLE
Edge no matching capabilities found

### ISSUE THREAD

**Issue by mjevtovic** [aerokube/selenoid#1013]
Hello,

I am trying to start tests on new browsers:edge:88.0 image but I am getting
```
org.openqa.selenium.SessionNotCreatedException: session not created: No matching capabilities found
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'Markos-MacBook-Pro.local', ip: '127.0.0.1', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.15.3', java.version: '1.8.0_242'
Driver info: driver.version: RemoteWebDriver
remote stacktrace: #0 0x55779fc49879 base::debug::CollectStackTrace()


	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$errorHandler$0(W3CHandshakeResponse.java:62)
	at org.openqa.selenium.remote.HandshakeResponse.lambda$getResponseFunction$0(HandshakeResponse.java:30)
	at org.openqa.selenium.remote.ProtocolHandshake.lambda$createSession$0(ProtocolHandshake.java:126)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958)
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:499)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:486)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:531)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:128)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:74)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:136)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:213)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:131)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:144)
	at Util.WebTest.create_driver(WebTest.java:226)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:220)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:53)
```

My capabilities are set as:
```

   DesiredCapabilities capabilities = new DesiredCapabilities();
            capabilities.setBrowserName("edge");
            capabilities.setVersion("88.0");
            capabilities.setCapability("enableVNC", true);
            capabilities.setCapability("enableVideo", false);
            logger.debug("Creating Remote edge WebDriver....");
            _driver = new RemoteWebDriver(
                    URI.create(SELENOID_URL).toURL(),
                    capabilities);

```
My browser.json on selenoid:

```
{
  "chrome": {
    "default": "86.0",
    "versions": {
      "86.0": {
        "image": "selenoid/chrome:86.0",
        "port": "4444",
        "path": "/",
        "privileged": "true"
      },
      "mobile-79.0": {
        "image": "selenoid/chrome-mobile:79.0",
        "port": "4444",
        "path": "/wd/hub",
        "env": [
          "EMULATOR_ARGS=-dns-server 8.8.8.8"
        ]
      },
      "mobile-75.0": {
        "image": "selenoid/chrome-mobile:75.0",
        "port": "4444",
        "path": "/wd/hub",
        "env": [
          "EMULATOR_ARGS=-dns-server 8.8.8.8"
        ]
      }
    }
  },
  "firefox": {
    "default": "82.0",
    "versions": {
      "82.0": {
        "image": "selenoid/firefox:82.0",
        "port": "4444",
        "path": "/wd/hub",
        "tmpfs": {
          "/tmp": "size=128m"
        }
      }
    }
  },
  "opera": {
    "default": "71.0",
    "versions": {
      "71.0": {
        "image": "selenoid/opera:71.0",
        "port": "4444",
        "path": "/",
        "privileged": true
      }
    }
  },
"edge": {
  "default": "88.0",
  "versions": {
    "88.0": {
      "image": "browsers/edge:88.0",
      "port": "4444",
      "path": "/"
    }
  }
}
}

```

In selenoid hub log:

```
2020/10/29 14:06:45 [-] [NEW_REQUEST] [unknown] [24.135.186.39]
2020/10/29 14:06:45 [-] [NEW_REQUEST_ACCEPTED] [unknown] [24.135.186.39]
2020/10/29 14:06:45 [22] [LOCATING_SERVICE] [edge] [88.0]
2020/10/29 14:06:45 [22] [USING_DOCKER] [edge] [88.0]
2020/10/29 14:06:45 [22] [CREATING_CONTAINER] [browsers/edge:88.0]
2020/10/29 14:06:45 [22] [STARTING_CONTAINER] [browsers/edge:88.0] [df2c78d51579c83399dc003255604803cbb6f3dac2a6fae8ffd35d47deb17817]
2020/10/29 14:06:45 [22] [CONTAINER_STARTED] [browsers/edge:88.0] [df2c78d51579c83399dc003255604803cbb6f3dac2a6fae8ffd35d47deb17817] [0.49s]
2020/10/29 14:06:46 [22] [SERVICE_STARTED] [browsers/edge:88.0] [df2c78d51579c83399dc003255604803cbb6f3dac2a6fae8ffd35d47deb17817] [0.41s]
2020/10/29 14:06:46 [22] [PROXY_TO] [df2c78d51579c83399dc003255604803cbb6f3dac2a6fae8ffd35d47deb17817] [http://172.18.0.4:4444/]
2020/10/29 14:06:46 [22] [SESSION_ATTEMPTED] [http://172.18.0.4:4444/] [1]
2020/10/29 14:06:46 [22] [SESSION_FAILED] [http://172.18.0.4:4444/] [500 Internal Server Error]
2020/10/29 14:06:46 [22] [REMOVING_CONTAINER] [df2c78d51579c83399dc003255604803cbb6f3dac2a6fae8ffd35d47deb17817]
2020/10/29 14:06:46 [22] [CONTAINER_REMOVED] [df2c78d51579c83399dc003255604803cbb6f3dac2a6fae8ffd35d47deb17817]
```
I am using latest selenoid/hub.

**Comment by vania-pooh** [comment]
@mjevtovic in recent browser versions all Selenoid-specific capabilities like `enableVNC` and `enableVideo` should go under a capability with `selenoid:options` key. https://aerokube.com/selenoid/latest/#_specifying_capabilities_via_protocol_extensions

**Comment by NetanelMosheCohen** [comment]
@mjevtovic Also you need to change in both code and browsers.json - "edge" to "MicrosoftEdge". Worked for me.
