### ISSUE TITLE
File not found error, when I try to upload file with Chrome and C#

### ISSUE THREAD

**Issue by dparadisZentelia** [aerokube/selenoid#1014]
I follow https://aerokube.com/selenoid/latest/#_uploading_files_to_browser, but I get this error:
```
OpenQA.Selenium.WebDriverException' occurred in WebDriver.dll but was not handled in user code: 'invalid argument: File not found : /Users/dannyparadis/selenoid/test.txt
  (Session info: chrome=86.0.4240.75)'
   at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteWebDriver.InternalExecute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteWebElement.Execute(String commandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteWebElement.SendKeys(String text)
```

Simple C# test to reproduce:
```
private IWebDriver GetDriverOnSelenoid()
        {
            ChromeOptions options = new ChromeOptions();
            options.AcceptInsecureCertificates = true;
            options.AddAdditionalCapability("screenResolution", "1920x1080x24", true);
            options.AddAdditionalCapability("enableVNC", true, true);
            ICapabilities caps = options.ToCapabilities();
            IWebDriver driver =  new RemoteWebDriver(new Uri("http://localhost:4444/wd/hub"), caps);
            driver.Manage().Window.Maximize();
            driver.Manage().Timeouts().ImplicitWait = TimeSpan.FromSeconds(5);
            return driver;
        }

        [Test]
        [Description("Test upload file with Selenoid")]
        public void TestUploadFileWithSelenoid()
        {
            IWebDriver d = GetDriverOnSelenoid();
            d.Navigate().GoToUrl("http://the-internet.herokuapp.com/upload");

            ((RemoteWebDriver)d).FileDetector = new DefaultFileDetector();

//The error line...
            d.FindElement(By.Id("file-upload")).SendKeys("/Users/dannyparadis/selenoid/test.txt");
            
            d.FindElement(By.Id("file-submit")).Click();

            string textDisplayOnThePage = d.FindElement(By.XPath("//body")).Text;
            AssertHelper.That(textDisplayOnThePage,Does.Contain("File Uploaded!"),"Page display [File Uploaded]");
            AssertHelper.That(textDisplayOnThePage,Does.Contain("text.txt"),"Page display [test.txt]");

            d.Close();
            d.Quit();

        }

```

browsers.json
```
{
    "chrome": {
        "default": "86.0",
        "versions": {
            "86.0": {
                "image": "selenoid/chrome:86.0",
                "port": "4444",
                "path": "/",
                "tmpfs": {
                    "/tmp": "size=128m"
                }
            }
        }
    }
}
```
I can run the same test in local without error.
I expected when I use the line: `((RemoteWebDriver)d).FileDetector = new DefaultFileDetector(); `, the file will be available on the docker session.
 
I tried the arg -enable-file-upload, without success, too.

Any idea where the problem is?

**Comment by vania-pooh** [comment]
@dparadisZentelia there is a similar Java example here: https://aerokube.com/selenoid/latest/#_uploading_files_to_browser

**Comment by dparadisZentelia** [comment]
I tried with Java and the file upload works fine.
Look like a problem with C# WebDriver.

**Comment by vania-pooh** [comment]
@dparadisZentelia related but not yet released fix. https://github.com/SeleniumHQ/selenium/pull/8586

**Comment by dparadisZentelia** [comment]
Base on the comment of @vania-pooh, I close this issue, because the problem is not in Selenoid but in C# Selenium.
https://github.com/SeleniumHQ/selenium/pull/8586
