### ISSUE TITLE
Support /json/list for devtools

### ISSUE THREAD

**Issue by NivedhaSenthil** [aerokube/selenoid#1023]
Currently /json/list which is a [standard protocol endpoint]( https://chromedevtools.github.io/devtools-protocol/) is not supported by [selenoid](https://github.com/aerokube/selenoid/blob/master/docs/devtools.adoc).

Below is a sample code that uses [chrome remote interface](https://github.com/cyrus-and/chrome-remote-interface) to replicate the issue since /json/list is not exposed. Exposing it will be helpful connecting to any open page in the particular browser session. 

```
const cri = require('chrome-remote-interface');
(async () => {
    let criClient;
    try {
        const axios = require('axios');
        const selenoidUrl = '127.0.0.1';
        const fs = require('fs');
        const { data } = await axios.post(
            `http://${selenoidUrl}:4444/wd/hub/session`,
            {
                "desiredCapabilities":
                {
                    browserName: "chrome",
                    browserVersion: "87.0",
                    "selenoid:options": {
                        sessionTimeout: '3m',
                        enableVnc: true
                    }
                }
            }
        );
        const sessionId = data.sessionId;
        const options = {
            target: `ws://${selenoidUrl}:4444/devtools/${sessionId}/`,
            alterPath: (path) => `/devtools/${sessionId}${path}` 
        };
        criClient= await cri(options).catch((e) => {
            console.log("Error connecting");
            console.log(e);
        });

        // create new page
        const newTargetId = (await criClient.Target.createTarget({url:"about:blank"})).targetId;

        // connect to new page
        await cri({host:selenoidUrl, port:"4444", target:newTargetId}, (client) => {
            console.log('Connected to new target!');
            criClient = client;
        }).on('error', (err) => {
            console.error(err);
        });

    } catch (error) {
        console.error(error);
    } finally {
        criClient.close();
    }
})();
```

Error generated now:

```
undefined:1
You are using Selenoid 1.10.0!
^

SyntaxError: Unexpected token Y in JSON at position 0
    at JSON.parse (<anonymous>)
    at /usr/local/lib/node_modules/chrome-remote-interface/lib/devtools.js:74:33
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/chrome-remote-interface/lib/external-request.js:32:17)
    at IncomingMessage.emit (events.js:326:22)
    at endReadableNT (_stream_readable.js:1252:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
```

**Comment by saikrishna321** [comment]
@vania-pooh This is the issue which I was discussing with you over chat.

**Comment by vania-pooh** [comment]
@NivedhaSenthil @saikrishna321 we intentionally do not support this API as it makes no sense. This API will return `127.0.0.1:<some-port>` as web-socket endpoint and this certainly will not work as everything is running in containers.

**Comment by NivedhaSenthil** [comment]
yes that makes sense, it would be an overkill to regenerate target list with updated details if selenoid has to expose.We will try wrapping up the connector to modify the ws url instead of using /json/list
