### ISSUE TITLE
Failed to start Firefox 22 and older

### ISSUE THREAD

**Issue by vania-pooh** [aerokube/selenoid#109]
Selenoid 1.3.0
```
2017/06/06 15:27:14 [1] [SESSION_ATTEMPTED] [unknown] [http://172.17.0.2:4444/wd/hub] [1]
2017/06/06 15:27:14 Unsolicited response received on idle HTTP channel starting with "0\r\n\r\n"; err=<nil>
2017/06/06 15:27:17 [1] [SESSION_FAILED] [unknown] [Bad response from http://172.17.0.2:4444/wd/hub - 500 java%2Eutil%2Econcurrent%2EExecutionException%3A+java%2Elang%2ENullPointerException]
```

```
org.openqa.selenium.WebDriverException: <html>
<head>
<title>Error 500 org.openqa.selenium.WebDriverException: java.util.concurrent.ExecutionException: java.lang.NullPointerException
Build info: version: '2.32.0', revision: '6c40c18', time: '2013-04-09 17:22:56'
System info: os.name: 'Linux', os.arch: 'amd64', os.version: '4.2.0-41-generic', java.version: '1.8.0_121'
Driver info: driver.version: unknown</title>
</head>
<body>
<h2>HTTP ERROR: 500</h2><pre>org.openqa.selenium.WebDriverException: java.util.concurrent.ExecutionException: java.lang.Nu
Command duration or timeout: 3.47 seconds
Build info: version: '2.53.1', revision: 'a36b8b1cd5757287168e54b817830adce9b0158d', time: '2016-06-30 19:26:09'
System info: host: 'localhost', ip: '127.0.0.1', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.9.5', java.version: '1.8.0_45'
Driver info: org.openqa.selenium.remote.RemoteWebDriver

	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:158)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:678)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:249)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:131)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:158)
	at ru.yandex.qatools.test.SeleniumTest.openDriver(SeleniumTest.java:284)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.junit.runners.Suite.runChild(Suite.java:127)
	at org.junit.runners.Suite.runChild(Suite.java:26)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:51)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
```

**Comment by vania-pooh** [comment]
Need to create client compatibility table. Because with 3.3.1 and Firefox 53 getting:
```
org.openqa.selenium.SessionNotCreatedException: Unable to create new remote session. desired capabilities = Capabilities [{browserName=firefox, version=53.0, platform=LINUX}], required capabilities = Capabilities [{}]
Build info: version: '3.3.1', revision: '5234b32', time: '2017-05-30 16:51:05 +0300'
System info: host: 'localhost', ip: 'fe80:0:0:0:5ef9:38ff:fe99:4a9c%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.9.5', java.version: '1.8.0_45'
Driver info: driver.version: RemoteWebDriver

	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:126)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:141)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:604)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:244)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:131)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:158)
	at ru.yandex.qatools.test.SeleniumTest.openDriver(SeleniumTest.java:284)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.junit.runners.Suite.runChild(Suite.java:127)
	at org.junit.runners.Suite.runChild(Suite.java:26)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:51)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)

```

**Comment by vania-pooh** [comment]
```
selenoid/firefox:3.6
selenoid: 1.3.0
Selenium 2.53.1 (also tested with 2.33.0)
```
When going to container directly - it works, when using Selenoid - does not.

**Comment by vania-pooh** [comment]
Here's HTTP exchange between Selenoid and container:
```
19:34:01.773999 POST /wd/hub/session HTTP/1.1
Content-Type: application/json; charset=utf-8
Content-Length: 84
Host: build-vm.haze.yandex.net:4444
Connection: Keep-Alive
User-Agent: Apache-HttpClient/4.5.1 (Java/1.8.0_45)
Accept-Encoding: gzip,deflate

{"desiredCapabilities":{"browserName":"firefox","version":"3.6","platform":"LINUX"}}

19:34:03.423511 HEAD /wd/hub HTTP/1.1
Host: 172.17.0.3:4444
User-Agent: Go-http-client/1.1

19:34:03.423836 HEAD /wd/hub HTTP/1.1
Host: 172.17.0.3:4444
User-Agent: Go-http-client/1.1

19:34:03.599834 HTTP/1.1 302 Moved Temporarily
Date: Wed, 07 Jun 2017 16:34:03 GMT
Server: Jetty/5.1.x (Linux/3.13.0-35-generic amd64 java/1.8.0_121
Expires: Thu, 01 Jan 1970 00:00:00 GMT
Cache-Control: no-cache
Location: http://172.17.0.3:4444/wd/hub/static/resource/hub.html
Content-Length: 0

19:34:03.600136 HEAD /wd/hub/static/resource/hub.html HTTP/1.1
Host: 172.17.0.3:4444
User-Agent: Go-http-client/1.1
Referer: http://172.17.0.3:4444/wd/hub

19:34:03.600152 HTTP/1.1 302 Moved Temporarily
Date: Wed, 07 Jun 2017 16:34:03 GMT
Server: Jetty/5.1.x (Linux/3.13.0-35-generic amd64 java/1.8.0_121
Expires: Thu, 01 Jan 1970 00:00:00 GMT
Cache-Control: no-cache
Location: http://172.17.0.3:4444/wd/hub/static/resource/hub.html
Content-Length: 0

19:34:03.601871 HEAD /wd/hub/static/resource/hub.html HTTP/1.1
Host: 172.17.0.3:4444
User-Agent: Go-http-client/1.1
Referer: http://172.17.0.3:4444/wd/hub

19:34:03.617937 HTTP/1.1 200 OK
Date: Wed, 07 Jun 2017 16:34:03 GMT
Server: Jetty/5.1.x (Linux/3.13.0-35-generic amd64 java/1.8.0_121
Expires: Thu, 01 Jan 1970 00:00:00 GMT
Cache-Control: no-cache
Transfer-Encoding: chunked

19:34:03.618807 HTTP/1.1 200 OK
Date: Wed, 07 Jun 2017 16:34:03 GMT
Server: Jetty/5.1.x (Linux/3.13.0-35-generic amd64 java/1.8.0_121
Expires: Thu, 01 Jan 1970 00:00:00 GMT
Cache-Control: no-cache
Transfer-Encoding: chunked

....


19:34:05.359256 HTTP/1.1 500 Internal Server Error
Content-Type: application/json
Date: Wed, 07 Jun 2017 16:34:05 GMT
Content-Length: 110

{"status":13,"value":{"message":"Post http://172.17.0.3:4444/wd/hub/session: malformed HTTP response \"0\""}}

```

**Comment by vania-pooh** [comment]
Fixed in https://github.com/aerokube/selenoid/pull/121.
