### ISSUE TITLE
How we can use "Chrome Extension" with Selenoid.

### ISSUE THREAD

**Issue by ankitjain082** [aerokube/selenoid#1116]
Hi,

I want to run few scenario with Ad Blocker on Chrome so tried to add "Adblock.crx" extension but not able to create session.
I have added "Adblock.crx" file in chrome using below code ::

**Code** :: options.addExtensions(pathObject.toFile());

**Error** :: Starting browser...
Capabilities: Capabilities {acceptSslCert: true, browser: chrome , browserName: chrome, goog:chromeOptions: {args: [], extensions: [Q3IyNAMAAAAZBAAAEqwECqYCMII...]}, name: Web_Desktop_US_DataRights, os: Linux, version: internal-latest}
Grid: US_Grid
org.openqa.selenium.remote.UnreachableBrowserException: Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'

Please help me to solve this.

Thanks,
Ankit Jain

**Comment by vania-pooh** [comment]
@ankitjain082 browser session logs could help to diagnose.

**Comment by ankitjain082** [comment]
Hi,

Here is Console logs ::

Starting browser...
Capabilities: Capabilities {acceptSslCert: true, browser: chrome , browserName: chrome, goog:chromeOptions: {args: [], extensions: [Q3IyNAMAAAAZBAAAEqwECqYCMII...]}, name: Web_Desktop_US_DataRights, os: Linux, version: internal-latest}
Grid: US_Grid
org.openqa.selenium.remote.UnreachableBrowserException: Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'Ankits-MacBook-Pro-2.local', ip: '2409:4043:2e84:aa61:98eb:1aa7:6e23:2bdd%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.14.6', java.version: '1.8.0_221'
Driver info: driver.version: RemoteWebDriver
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:573)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:213)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:131)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:144)
	at tests.WebDriverThread.run(BaseTest.java:498)
Caused by: java.net.ConnectException: Failed to connect to /158.85.231.21:4445
	at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:247)
	at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:165)
	at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:257)
	at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:135)
	at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:114)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
	at okhttp3.RealCall.execute(RealCall.java:77)
	at org.openqa.selenium.remote.internal.OkHttpClient.execute(OkHttpClient.java:103)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:105)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:74)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:136)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
	... 4 more
Caused by: java.net.ConnectException: Operation timed out (Connection timed out)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at okhttp3.internal.platform.Platform.connectSocket(Platform.java:129)
	at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:245)
	... 26 more
Exception in thread "Thread-1" java.lang.RuntimeException: Failed to start webdriver, Error: Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'Ankits-MacBook-Pro-2.local', ip: '2409:4043:2e84:aa61:98eb:1aa7:6e23:2bdd%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.14.6', java.version: '1.8.0_221'
Driver info: driver.version: RemoteWebDriver
	at tests.WebDriverThread.run(BaseTest.java:519)
Caused by: org.openqa.selenium.remote.UnreachableBrowserException: Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'Ankits-MacBook-Pro-2.local', ip: '2409:4043:2e84:aa61:98eb:1aa7:6e23:2bdd%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.14.6', java.version: '1.8.0_221'
Driver info: driver.version: RemoteWebDriver
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:573)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:213)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:131)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:144)
	at tests.WebDriverThread.run(BaseTest.java:498)
Caused by: java.net.ConnectException: Failed to connect to /158.85.231.21:4445
	at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:247)
	at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:165)
	at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:257)
	at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:135)
	at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:114)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
	at okhttp3.RealCall.execute(RealCall.java:77)
	at org.openqa.selenium.remote.internal.OkHttpClient.execute(OkHttpClient.java:103)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:105)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:74)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:136)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
	... 4 more
Caused by: java.net.ConnectException: Operation timed out (Connection timed out)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at okhttp3.internal.platform.Platform.connectSocket(Platform.java:129)
	at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:245)
	... 26 more
java.lang.NullPointerException
********* Test Method : [Web_Desktop_US_DataRights, /data-rights] -  Failed *************
Exception: ->
java.lang.NullPointerException
	at tests.BaseTest.getScreenShots(BaseTest.java:158)
	at tests.BaseTest.comparePage(BaseTest.java:98)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:75)
	at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by vania-pooh** [comment]
@ankitjain082 I need browser container logs from Selenoid.

**Comment by ankitjain082** [comment]
@vania-pooh I am not able to get any log in GGR and Slenoid container.
I have follow below steps:
1 Clear the logs for GGR and Selenoid Container.
2 Ran my test **with add "Adblock.crx" file** in Google chrome options and got below error :
**Error : org.openqa.selenium.remote.UnreachableBrowserException: Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'**
3 Run command sudo docker logs container id but didn't get any log for GGR and selenoid.
4 I ran my test **without add "Adblock.crx" file** and it was working fine.

Note : I ran same test case with add "Adblock.crx" file in Google chrome options on Browser Stack grid and it was working fine.

Let me know if you need any other info.

**Comment by ankitjain082** [comment]
@vania-pooh can you please help me for the same.

**Comment by ankitjain082** [comment]
@vania-pooh could you please share your thoughts on this.

**Comment by vania-pooh** [comment]
@ankitjain082 at least what's in `docker logs selenoid`?

**Comment by ankitjain082** [comment]
@vania-pooh it's blank, I'll share screen shot for the same.

**Comment by vania-pooh** [comment]
@ankitjain082 `Operation timed out (Connection timed out)` usually means you have Firewall blocking Selenoid port 4444.

**Comment by Ankit-TWC** [comment]
@vania-pooh I am able to run my test successfully on same GGR and Selenoid VM but getting issue with with "Adblock.crx" file.

**Comment by Ankit-TWC** [comment]
@vania-pooh I am getting below error ::

Error : org.openqa.selenium.remote.UnreachableBrowserException: Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03

**Comment by vania-pooh** [comment]
@Ankit-TWC that means "something is wrong". Without details it's impossible to diagnose.

**Comment by Dor-bl** [comment]
@Ankit-TWC Why do you convert the path of the .Crx to a file?
`options.addExtensions(pathObject.toFile());`
On .NET we pass it as a string

**Comment by gdonati78** [comment]
Something like https://github.com/aerokube/selenoid/issues/571#issuecomment-437802575 worked for me

**Comment by ankitjain082** [comment]
Thanks @gdonati78, I'll try and let you know.

**Comment by or1k** [comment]
@Ankit-TWC @ankitjain082 Hello, there is a solution?
I have a similar problem, when I run a test with an extension and the test enters the queue - it crashes with the same error.

`org.openqa.selenium.remote.UnreachableBrowserException: Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.
Build info: version: '4.0.0-alpha-2', revision: 'f148142cf8', time: '2019-07-01T20:55:26'
System info: host: 'DESKTOP-NMMTF1R', ip: '26.190.126.197', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '11.0.6'
Driver info: driver.version: RemoteWebDriver`

If there are free containers, the test runs successfully.
