### ISSUE TITLE
Runtime error in selenoid on windows: Docker return empty bindings announced 

### ISSUE THREAD

**Issue by lislon** [aerokube/selenoid#1158]
I have the same issue #1058 and while debuging found an error that happens on windows 10 (both on Hyper-V and WSL2)

*Reproduce steps:*
1. Windows 10 + Docker Desktop 4.1.1
2. Build and run selenoid from `1.10.7` branch
3. Connect to selenoid session 

*Actual result:*
I got error in selenoid logs:
```
2021/11/21 18:21:42 [0] [CREATING_CONTAINER] [selenoid/chrome]
2021/11/21 18:21:42 [0] [STARTING_CONTAINER] [selenoid/chrome] [bd15d5565c1a2fc3bb74e1d7fa80392adcefda8e4a2a6be628f7edc7851d2671]
2021/11/21 18:21:44 [0] [CONTAINER_STARTED] [selenoid/chrome] [bd15d5565c1a2fc3bb74e1d7fa80392adcefda8e4a2a6be628f7edc7851d2671] [1.41s]
2021/11/21 18:21:44 http: panic serving 127.0.0.1:56889: runtime error: index out of range [0] with length 0
goroutine 9 [running]:
net/http.(*conn).serve.func1()
	C:/Program Files/Go/src/net/http/server.go:1801 +0x13a
panic({0x137a2c0, 0xc000116048})
	C:/Program Files/Go/src/runtime/panic.go:1047 +0x262
github.com/aerokube/selenoid/service.getHostPort.func3({0xc0003cfde0, 0x4}, {0xc000408e20, 0x8})
	C:/Users/ele/src/go/selenoid/service/docker.go:458 +0xca
github.com/aerokube/selenoid/service.getHostPort({{0x0, 0x0}, 0x0, 0x0, 0x0, {0x13a5c48, 0x7}, {0x0, 0x0}, 0x6fc23ac00, ...}, ...)
	C:/Users/ele/src/go/selenoid/service/docker.go:467 +0x2ec
github.com/aerokube/selenoid/service.(*Docker).StartWithCancel(0xc000480000)
	C:/Users/ele/src/go/selenoid/service/docker.go:214 +0x2268
main.create({0x13ffe58, 0xc00042a0e0}, 0xc000418200)
	C:/Users/ele/src/go/selenoid/selenoid.go:193 +0x13e3
net/http.HandlerFunc.ServeHTTP(0x13ca188, {0x13ffe58, 0xc00042a0e0}, 0xc000418200)
	C:/Program Files/Go/src/net/http/server.go:2046 +0x43
github.com/aerokube/selenoid/protect.(*Queue).Protect.func1({0x13ffe58, 0xc00042a0e0}, 0xc000418200)
	C:/Users/ele/src/go/selenoid/protect/queue.go:76 +0x47d
net/http.HandlerFunc.ServeHTTP(0xc00043a348, {0x13ffe58, 0xc00042a0e0}, 0xc000418200)
	C:/Program Files/Go/src/net/http/server.go:2046 +0x43
github.com/aerokube/selenoid/protect.(*Queue).Check.func1({0x13ffe58, 0xc00042a0e0}, 0xc000418200)
	C:/Users/ele/src/go/selenoid/protect/queue.go:53 +0x26a
net/http.HandlerFunc.ServeHTTP(0xc00043a360, {0x13ffe58, 0xc00042a0e0}, 0xc000418200)
	C:/Program Files/Go/src/net/http/server.go:2046 +0x43
github.com/aerokube/selenoid/protect.(*Queue).Try.func1({0x13ffe58, 0xc00042a0e0}, 0xc000418200)
	C:/Users/ele/src/go/selenoid/protect/queue.go:35 +0x125
net/http.HandlerFunc.ServeHTTP(0xc00043a378, {0x13ffe58, 0xc00042a0e0}, 0xc000418200)
	C:/Program Files/Go/src/net/http/server.go:2046 +0x43
main.post.func1({0x13ffe58, 0xc00042a0e0}, 0xc000418200)
	C:/Users/ele/src/go/selenoid/main.go:258 +0x125
net/http.HandlerFunc.ServeHTTP(0xc00040e3f0, {0x13ffe58, 0xc00042a0e0}, 0xc000418200)
	C:/Program Files/Go/src/net/http/server.go:2046 +0x43
net/http.(*ServeMux).ServeHTTP(0xc00040c3c0, {0x13ffe58, 0xc00042a0e0}, 0xc000418200)
	C:/Program Files/Go/src/net/http/server.go:2424 +0x135
main.handler.func1({0x13ffe58, 0xc00042a0e0}, 0xc000418200)
	C:/Users/ele/src/go/selenoid/main.go:329 +0x1bd
net/http.HandlerFunc.ServeHTTP(0x13ca1a0, {0x13ffe58, 0xc00042a0e0}, 0xc000418200)
	C:/Program Files/Go/src/net/http/server.go:2046 +0x43
net/http.(*ServeMux).ServeHTTP(0xc000138080, {0x13ffe58, 0xc00042a0e0}, 0xc000418200)
	C:/Program Files/Go/src/net/http/server.go:2424 +0x135
net/http.serverHandler.ServeHTTP({0xc000144000}, {0x13ffe58, 0xc00042a0e0}, 0xc000418200)
	C:/Program Files/Go/src/net/http/server.go:2878 +0x47a
net/http.(*conn).serve(0xc0000a6140, {0x1402eb8, 0xc00040c280})
	C:/Program Files/Go/src/net/http/server.go:1929 +0x18b8
created by net/http.(*Server).Serve
	C:/Program Files/Go/src/net/http/server.go:3033 +0xa38
```
The error happens on this line:
```
return net.JoinHostPort("127.0.0.1", stat.NetworkSettings.Ports[port][0].HostPort)
```

The `stat.NetworkSettings.Ports[port]` is actually empty array. If I put `sleep 1s` after starting container, but before getting stat, everything is working fine, including videorecording:

```
       // ...docker.go:163
	err = cl.ContainerStart(ctx, browserContainerId, types.ContainerStartOptions{})
        //...
        time.Sleep(1 * time.Second)
        stat, err := cl.ContainerInspect(ctx, browserContainerId)
```

Looks like docker needs some time to bind ports before container can usable

**Comment by vania-pooh** [comment]
Seems to be the same as #1102.
