### ISSUE TITLE
Selenoid ignore -session-attempt-timeout?

### ISSUE THREAD

**Issue by zidex** [aerokube/selenoid#1208]
Hello!

We run selenoid from docker-compose:

```
  selenoid:
    network_mode: bridge
    image: aerokube/selenoid:latest-release
    container_name: "selenoid"
    volumes:
      - "$PWD:/etc/selenoid/:ro"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "$PWD/logs:/opt/selenoid/logs/"
    command: -session-attempt-timeout 60s -limit ${LIMIT:-4} -save-all-logs -log-output-dir /opt/selenoid/logs
    ports:
      - "4444:4444"
```

in docker container `ps -ef` says:

> /usr/bin/selenoid -listen :4444 -conf /etc/selenoid/browsers.json -video-output-dir /opt/selenoid/video/ -session-attempt-timeout 60s -limit 11 -save-all-logs -log-output-dir /opt/selenoid/logs

But in logs timeout 30s:

> 2022-04-14T23:09:06.691478769Z 20
> 2022-04-14T23:09:06.699275123Z Waiting X server...
> 2022-04-14T23:09:06.826546260Z Waiting X server...
> 2022-04-14T23:09:06.829301992Z Logging to: /dev/null
> 2022-04-14T23:09:06.937748152Z Waiting X server...
> 2022-04-14T23:09:07.043379310Z Waiting X server...
> 2022-04-14T23:09:07.150639639Z Waiting X server...
> 2022-04-14T23:09:07.255567937Z Waiting X server...
> 2022-04-14T23:09:07.360276587Z Waiting X server...
> 2022-04-14T23:09:07.465207015Z Waiting X server...
> 2022-04-14T23:09:07.569755398Z Waiting X server...
> 2022-04-14T23:09:07.675106968Z Waiting X server...
> 2022-04-14T23:09:07.779862080Z Waiting X server...
> 2022-04-14T23:09:07.884678364Z Waiting X server...
> 2022-04-14T23:09:07.989742824Z Waiting X server...
> 2022-04-14T23:09:08.094452105Z Waiting X server...
> 2022-04-14T23:09:08.199502757Z Waiting X server...
> 2022-04-14T23:09:08.304578041Z Waiting X server...
> 2022-04-14T23:09:08.409668070Z Waiting X server...
> 2022-04-14T23:09:08.515684689Z Waiting X server...
> 2022-04-14T23:09:08.620627473Z Waiting X server...
> 2022-04-14T23:09:08.750872390Z Waiting X server...
> 2022-04-14T23:09:08.861922975Z Waiting X server...
> 2022-04-14T23:09:08.977485143Z 
> 2022-04-14T23:09:08.977518593Z  --- x11vnc loop: 1 ---
> 2022-04-14T23:09:08.977523782Z 
> 2022-04-14T23:09:08.977527986Z 2022/04/14 23:09:08 [-] [INIT] [Loading configuration files...]
> 2022-04-14T23:09:08.977731776Z 2022/04/14 23:09:08 [-] [INIT] [Loaded configuration from /tmp/browsers.json]
> 2022-04-14T23:09:08.977950655Z 2022/04/14 23:09:08 [-] [INIT] [Timezone: UTC]
> 2022-04-14T23:09:08.977966465Z 2022/04/14 23:09:08 [-] [INIT] [Listening on :4444]
> 2022-04-14T23:09:09.014090029Z 2022/04/14 23:09:09 [-] [NEW_REQUEST] [unknown] [172.17.0.2]
> 2022-04-14T23:09:09.014104491Z 2022/04/14 23:09:09 [-] [NEW_REQUEST_ACCEPTED] [unknown] [172.17.0.2]
> 2022-04-14T23:09:09.014551981Z 2022/04/14 23:09:09 [0] [LOCATING_SERVICE] [firefox] []
> 2022-04-14T23:09:09.014568139Z 2022/04/14 23:09:09 [-] [DEFAULT_VERSION] [Using default version: 94.0]
> 2022-04-14T23:09:09.014573102Z 2022/04/14 23:09:09 [0] [USING_DRIVER] [firefox] [94.0]
> 2022-04-14T23:09:09.014577100Z 2022/04/14 23:09:09 [0] [ALLOCATING_PORT]
> 2022-04-14T23:09:09.014956369Z 2022/04/14 23:09:09 [0] [ALLOCATED_PORT] [41573]
> 2022-04-14T23:09:09.014977785Z 2022/04/14 23:09:09 [0] [STARTING_PROCESS] [[/usr/bin/geckodriver --port=41573]]
> 2022-04-14T23:09:09.016028465Z 1649977749015	geckodriver	INFO	Listening on 127.0.0.1:41573
> 2022-04-14T23:09:09.066719425Z 2022/04/14 23:09:09 [0] [PROCESS_STARTED] [147] [0.05s]
> 2022-04-14T23:09:09.066764259Z 2022/04/14 23:09:09 [0] [PROXY_TO] [http://127.0.0.1:41573]
> 2022-04-14T23:09:09.066972209Z 2022/04/14 23:09:09 [0] [SESSION_ATTEMPTED] [http://127.0.0.1:41573] [1]
> 2022-04-14T23:09:09.068555568Z 1649977749068	mozrunner::runner	INFO	Running command: "/usr/bin/firefox" "--marionette" "-foreground" "-no-remote" "-profile" "/tmp/rust_mozprofileAtf4Dg"
> 2022-04-14T23:09:09.478758863Z  --- x11vnc loop: waiting for: 251
> 2022-04-14T23:09:09.478792125Z 
> 2022-04-14T23:09:09.528670241Z PORT=5900
> 2022-04-14T23:09:20.404666027Z [GFX1-]: glxtest: libpci missing
> 2022-04-14T23:09:20.404678336Z [GFX1-]: glxtest: libEGL missing
> 2022-04-14T23:09:22.359663939Z 1649977762359	Marionette	INFO	Marionette enabled
> 2022-04-14T23:09:38.253906220Z console.warn: SearchSettings: "get: No settings file exists, new profile?" (new NotFoundError("Could not open the file at /tmp/rust_mozprofileAtf4Dg/search.json.mozlz4", (void 0)))
> **2022-04-14T23:09:39.067596885Z 2022/04/14 23:09:39 [0] [SESSION_ATTEMPT_TIMED_OUT] [30s]**
> 2022-04-14T23:09:39.067624136Z 2022/04/14 23:09:39 [0] [SESSION_FAILED] [http://127.0.0.1:41573] [New session attempts retry count exceeded]
> 2022-04-14T23:09:39.067629282Z 2022/04/14 23:09:39 [0] [TERMINATING_PROCESS] [147]
> 2022-04-14T23:09:39.068050328Z 2022/04/14 23:09:39 [0] [TERMINATED_PROCESS] [147] [0.00s]

**Comment by vania-pooh** [comment]
@zidex any error message in test log?

**Comment by zidex** [comment]
[HandlersIT.copyVariable(Browser)[2]] java.lang.RuntimeException: Failed to create driver
	at core.BaseTest.initDriver(BaseTest.java:107)
	at BaseComponentIT.openBrowserAndLogin(BaseComponentIT.java:78)
	at BaseComponentIT.openBrowserAndStartProcess(BaseComponentIT.java:83)
	at HandlersIT.copyVariable(HandlersIT.java:32)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:725)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:149)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:140)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestTemplateMethod(TimeoutExtension.java:92)
	at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$7(TestMethodTestDescriptor.java:214)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:210)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:135)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:66)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:151)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at org.junit.platform.engine.support.hierarchical.ForkJoinPoolHierarchicalTestExecutorService$ExclusiveTask.compute(ForkJoinPoolHierarchicalTestExecutorService.java:185)
	at java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:189)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinTask.doJoin(ForkJoinTask.java:389)
	at java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:1001)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask$DefaultDynamicTestExecutor.awaitFinished(NodeTestTask.java:236)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:158)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at org.junit.platform.engine.support.hierarchical.ForkJoinPoolHierarchicalTestExecutorService$ExclusiveTask.compute(ForkJoinPoolHierarchicalTestExecutorService.java:185)
	at java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:189)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinTask.doJoin(ForkJoinTask.java:389)
	at java.util.concurrent.ForkJoinTask.join(ForkJoinTask.java:719)
	at org.junit.platform.engine.support.hierarchical.ForkJoinPoolHierarchicalTestExecutorService.joinConcurrentTasksInReverseOrderToEnableWorkStealing(ForkJoinPoolHierarchicalTestExecutorService.java:162)
	at org.junit.platform.engine.support.hierarchical.ForkJoinPoolHierarchicalTestExecutorService.invokeAll(ForkJoinPoolHierarchicalTestExecutorService.java:136)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at org.junit.platform.engine.support.hierarchical.ForkJoinPoolHierarchicalTestExecutorService$ExclusiveTask.compute(ForkJoinPoolHierarchicalTestExecutorService.java:185)
	at java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:189)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
	Suppressed: java.lang.NullPointerException
		at core.BaseTest$ScreenWatcher.takeScreen(BaseTest.java:164)
		at BaseComponentIT.exit(BaseComponentIT.java:71)
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.lang.reflect.Method.invoke(Method.java:498)
		at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:725)
		at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
		at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
		at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:149)
		at org.junit.jupiter.engine.extension.TimeoutExtension.interceptLifecycleMethod(TimeoutExtension.java:126)
		at org.junit.jupiter.engine.extension.TimeoutExtension.interceptAfterEachMethod(TimeoutExtension.java:108)
		at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
		at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
		at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
		at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
		at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
		at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
		at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
		at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98)
		at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.invokeMethodInExtensionContext(ClassBasedTestDescriptor.java:506)
		at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$synthesizeAfterEachMethodAdapter$22(ClassBasedTestDescriptor.java:496)
		at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeAfterEachMethods$10(TestMethodTestDescriptor.java:240)
		at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeAllAfterMethodsOrCallbacks$13(TestMethodTestDescriptor.java:273)
		at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
		at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeAllAfterMethodsOrCallbacks$14(TestMethodTestDescriptor.java:273)
		at java.util.ArrayList.forEach(ArrayList.java:1257)
		at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeAllAfterMethodsOrCallbacks(TestMethodTestDescriptor.java:272)
		at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeAfterEachMethods(TestMethodTestDescriptor.java:238)
		at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:139)
		... 45 more
	Suppressed: java.lang.NullPointerException
		at core.BaseTest.tearDown(BaseTest.java:68)
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.lang.reflect.Method.invoke(Method.java:498)
		at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:725)
		at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
		at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
		at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:149)
		at org.junit.jupiter.engine.extension.TimeoutExtension.interceptLifecycleMethod(TimeoutExtension.java:126)
		at org.junit.jupiter.engine.extension.TimeoutExtension.interceptAfterEachMethod(TimeoutExtension.java:108)
		at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
		at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
		at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
		at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
		at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
		at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
		at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
		at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98)
		at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.invokeMethodInExtensionContext(ClassBasedTestDescriptor.java:506)
		at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$synthesizeAfterEachMethodAdapter$22(ClassBasedTestDescriptor.java:496)
		at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeAfterEachMethods$10(TestMethodTestDescriptor.java:240)
		at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeAllAfterMethodsOrCallbacks$13(TestMethodTestDescriptor.java:273)
		at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
		at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeAllAfterMethodsOrCallbacks$14(TestMethodTestDescriptor.java:273)
		at java.util.ArrayList.forEach(ArrayList.java:1257)
		at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeAllAfterMethodsOrCallbacks(TestMethodTestDescriptor.java:272)
		at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeAfterEachMethods(TestMethodTestDescriptor.java:238)
		at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:139)
		... 45 more
Caused by: org.openqa.selenium.WebDriverException: New session attempts retry count exceeded (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 45.47 seconds
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'builder', ip: '10.10.31.72', os.name: 'Linux', os.arch: 'amd64', os.version: '4.9.0-18-amd64', java.version: '1.8.0_201'
Driver info: driver.version: RemoteWebDriver
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:214)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:166)
	at org.openqa.selenium.remote.JsonWireProtocolResponse.lambda$errorHandler$0(JsonWireProtocolResponse.java:54)
	at org.openqa.selenium.remote.HandshakeResponse.lambda$getResponseFunction$0(HandshakeResponse.java:30)
	at org.openqa.selenium.remote.ProtocolHandshake.lambda$createSession$0(ProtocolHandshake.java:126)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958)
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:128)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:74)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:136)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:213)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:131)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:144)
	at core.BaseTest.initDriver(BaseTest.java:104)
	... 70 more

**Comment by vania-pooh** [comment]
@zidex what is the value of `path` parameter for this browser version in `browsers.json`?

**Comment by zidex** [comment]
browser.json:


```
{
  "firefox": {
    "default": "94.0",
    "versions": {
      "94.0": {
        "image": "selenoid/firefox:94.0",
        "port": "4444",
        "path": "/wd/hub",
        "tmpfs": {
          "/tmp": "size=512m"
        }
      }
    }
  },
  "chrome": {
    "default": "98.0",
    "versions": {
      "98.0": {
        "image": "selenoid/chrome:98.0",
        "port": "4444",
        "tmpfs": {
          "/tmp": "size=512m"
        }
      }
    }
  }
}
```

**Comment by vania-pooh** [comment]
@zidex I would then launch browser image manually and take a look at VNC.
```
$ docker run --rm -it -p 4444:4444 -p 5900:5900 selenoid/firefox:94.0
```

Then you connect to port 5900 with a VNC client and password `selenoid`. Then you launch your test against: `http://localhost:4444/wd/hub`

**Comment by zidex** [comment]
I have a question why selenoid ignores  parameter -session-attempt-timeout ?
I run it with a parameter **-session-attempt-timeout 60s** or **-session-attempt-timeout 1m**
But in the log:
2022-04-14T23:09:39.067596885Z 2022/04/14 23:09:39 [0] [SESSION_ATTEMPT_TIMED_OUT] [**30s**]

**Comment by vania-pooh** [comment]
@zidex are you seeing this in Selenoid logs or in Firefox browser image logs?

**Comment by zidex** [comment]
I see such messages in files like selenoid0b2a3b67dd4565514c471a15a7c2e0ae.log from the directory /opt/selenoid/logs in selenoid docker-container

**Comment by vania-pooh** [comment]
@zidex Firefox images have a separate Selenoid instance inside where this flag is not configurable. For other browser types this should not reproduce.

**Comment by zidex** [comment]
Thanks. In most cases, the tests work fine, but sometimes this happens. The reason has not yet been understood. Any suggestions why this might happen?

**Comment by vania-pooh** [comment]
@zidex I would take a look at host machine system metrics. Probably it's happening when you overload the host.

**Comment by zidex** [comment]
Moved the launch of tests to a less loaded server.
But today I got this error:

2022-04-21T00:08:49.073818143Z 1650499729072	Marionette	FATAL	Remote protocol server failed to start: Error: Could not bind to port 35372 (NS_ERROR_SOCKET_ADDRESS_IN_USE)(chrome://remote/content/marionette/server.js:84:17) JS Stack trace: set acceptConnections@server.js:84:17

**Comment by vania-pooh** [comment]
@zidex marionette is a built-in Firefox server used for browser automation. Never seen this error before.
