### ISSUE TITLE
Unable to read value to convert for class org.openqa.selenium.remote.Response 

### ISSUE THREAD

**Issue by RianAshes** [aerokube/selenoid#1243]
Situation:
I have two remote servers in amazon, both have the same version of selenoid and docker installed, autotests run fine on one server, the following error occurs on the second:

```
jivosite suite > Tests > com.jivosite.tests.DialogTests > chatHistoryCheck FAILED
    org.openqa.selenium.remote.UnreachableBrowserException: Error communicating with the remote browser. It may have died.
    Build info: version: '4.1.2', revision: '9a5a329c5a'
    System info: host: 'myhost', ip: 'myip', os.name: 'Linux', os.arch: 'amd64', os.version: '3.10.0-1160.53.1.el7.x86_64', java.version: '11.0.14.1'
    Driver info: org.openqa.selenium.remote.RemoteWebDriver
    Command: [6567c4a1acc7d9af7761313eb0dec54e, get {url=myurl}]
    Capabilities {acceptInsecureCerts: false, acceptSslCerts: false, browserConnectionEnabled: false, browserName: chrome, chrome: {chromedriverVersion: 99.0.4844.51 (d537ec02474b5..., userDataDir: /tmp/.com.google.Chrome.04V9iZ}, cssSelectorsEnabled: true, databaseEnabled: false, goog:chromeOptions: {debuggerAddress: localhost:34665}, handlesAlerts: true, hasTouchScreen: false, javascriptEnabled: true, locationContextEnabled: true, mobileEmulationEnabled: false, nativeEvents: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: LINUX, platformName: LINUX, proxy: Proxy(), rotatable: false, setWindowRect: true, strictFileInteractability: false, takesHeapSnapshot: true, takesScreenshot: true, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unexpectedAlertBehaviour: accept, unhandledPromptBehavior: accept, version: 99.0.4844.51, webStorageEnabled: true, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true}
    Session ID: 6567c4a1acc7d9af7761313eb0dec54e
        at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:582)
        at org.openqa.selenium.remote.RemoteWebDriver.get(RemoteWebDriver.java:327)
        at com.jivosite.fw.HelperWebDriver.openUrl(HelperWebDriver.java:359)
        at com.jivosite.fw.AuthorizationHelper.openJivoApp(AuthorizationHelper.java:132)
        at com.jivosite.tests.DialogTests.chatHistoryCheck(DialogTests.java:156)

        Caused by:
        java.lang.IllegalArgumentException: Cannot decode response content: 
            at org.openqa.selenium.remote.codec.AbstractHttpResponseCodec.decode(AbstractHttpResponseCodec.java:86)
            at org.openqa.selenium.remote.codec.AbstractHttpResponseCodec.decode(AbstractHttpResponseCodec.java:47)
            at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:184)
            at org.openqa.selenium.remote.TracedCommandExecutor.execute(TracedCommandExecutor.java:51)
            at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:558)
            ... 4 more

            Caused by:
            org.openqa.selenium.json.JsonException: Unable to parse: 
                at org.openqa.selenium.json.Json.toType(Json.java:57)
                at org.openqa.selenium.json.Json.toType(Json.java:50)
                at org.openqa.selenium.remote.codec.AbstractHttpResponseCodec.decode(AbstractHttpResponseCodec.java:83)
                ... 8 more

                Caused by:
                org.openqa.selenium.json.JsonException: Unable to read value to convert for class org.openqa.selenium.remote.Response
                Build info: version: '4.1.2', revision: '9a5a329c5a'
                System info: host: 'myhost', ip: 'myip', os.name: 'Linux', os.arch: 'amd64', os.version: '3.10.0-1160.53.1.el7.x86_64', java.version: '11.0.14.1'
                Driver info: driver.version: HelperWebDriver
                    at org.openqa.selenium.json.StaticInitializerCoercer.lambda$apply$0(StaticInitializerCoercer.java:55)
                    at org.openqa.selenium.json.JsonTypeCoercer.lambda$buildCoercer$6(JsonTypeCoercer.java:145)
                    at org.openqa.selenium.json.JsonTypeCoercer.coerce(JsonTypeCoercer.java:127)
                    at org.openqa.selenium.json.Json.toType(Json.java:71)
                    at org.openqa.selenium.json.Json.toType(Json.java:55)
                    ... 10 more
```

I've tried several chromedriver versions, and all of them have similar errors. 
Also tried re-install docker and selenoid - and no effect.

Maybe you can recommend something to me, because I'm out of ideas.

**Comment by vania-pooh** [comment]
@RianAshes probably you just run out of memory and browser crashes.

**Comment by RianAshes** [comment]
Nope. It's fresh install, and here is 16 Gb ram, 100 Gb free disk space and nothing else on this server. Also today i tried create three more servers, and all of them have the same problem.

**Comment by vania-pooh** [comment]
@RianAshes what is your Selenoid image?

**Comment by RianAshes** [comment]
1.10.7
![image](https://user-images.githubusercontent.com/4927849/177093445-253556cc-31ce-4891-b1a8-bf2cb39b2e70.png)

**Comment by RianAshes** [comment]
Maybe there is a way to get the logs of this request to understand what is going wrong?

**Comment by vania-pooh** [comment]
@RianAshes you can try to run the same test with `enableVNC=true` capability and check in Selenoid UI what's going on.

**Comment by RianAshes** [comment]
I've tried this already. Selenoid start container with required browser, and close it after 60 seconds by timeout.
Also - logs from "docker selenoid logs":
```
2022/07/08 12:43:21 [-] [NEW_REQUEST] [unknown] [{request_ip}]
2022/07/08 12:43:21 [-] [NEW_REQUEST_ACCEPTED] [unknown] [{request_ip}]
2022/07/08 12:43:21 [0] [LOCATING_SERVICE] [chrome] [99.0]
2022/07/08 12:43:21 [0] [USING_DOCKER] [chrome] [99.0]
2022/07/08 12:43:21 [0] [CREATING_CONTAINER] [selenoid/chrome:99.0]
2022/07/08 12:43:21 [0] [STARTING_CONTAINER] [selenoid/chrome:99.0] [96e271d3c15bb7ec9642a76f81aa0cbbb6bc7911f27ae547377010604bdf4e69]
2022/07/08 12:43:21 [0] [CONTAINER_STARTED] [selenoid/chrome:99.0] [96e271d3c15bb7ec9642a76f81aa0cbbb6bc7911f27ae547377010604bdf4e69] [0.23s]
2022/07/08 12:43:22 [0] [SERVICE_STARTED] [selenoid/chrome:99.0] [96e271d3c15bb7ec9642a76f81aa0cbbb6bc7911f27ae547377010604bdf4e69] [0.86s]
2022/07/08 12:43:22 [0] [PROXY_TO] [96e271d3c15bb7ec9642a76f81aa0cbbb6bc7911f27ae547377010604bdf4e69] [http://172.18.0.4:4444/]
2022/07/08 12:43:22 [0] [SESSION_ATTEMPTED] [{host}] [1]
2022/07/08 12:43:23 [0] [SESSION_CREATED] [508688050243e557f919c73c52ca72c2] [1] [2.20s]
2022/07/08 12:44:24 [2] [SESSION_TIMED_OUT] [508688050243e557f919c73c52ca72c2]
2022/07/08 12:44:24 [3] [SESSION_DELETED] [508688050243e557f919c73c52ca72c2]
2022/07/08 12:44:54 [2] [DELETE_FAILED] [508688050243e557f919c73c52ca72c2] [Delete "http://127.0.0.1:4444/wd/hub/session/508688050243e557f919c73c52ca72c2": context deadline exceeded]
2022/07/08 12:44:54 [3] [CLIENT_DISCONNECTED] [unknown] [127.0.0.1] [Error: context canceled]
2022/07/08 12:44:54 [0] [REMOVING_CONTAINER] [96e271d3c15bb7ec9642a76f81aa0cbbb6bc7911f27ae547377010604bdf4e69]
2022/07/08 12:44:54 [2] [CLIENT_DISCONNECTED] [unknown] [{request_ip}] [Error: EOF]
2022/07/08 12:44:54 [0] [CONTAINER_REMOVED] [96e271d3c15bb7ec9642a76f81aa0cbbb6bc7911f27ae547377010604bdf4e69]
```

**Comment by RianAshes** [comment]
Any ideas? Or maybe recomendations how to get response log?

**Comment by RianAshes** [comment]
Problem still not solved. Any help? Please?

**Comment by vania-pooh** [comment]
@RianAshes please check for out of memory errors in `dmesg` and `/var/log/syslog` output.

**Comment by vania-pooh** [comment]
@RianAshes you can also do `tcpdump` like this:

```
# tcpdump -A -i eth0 'tcp port 4444'
```

Make sure you are using correct network interface name instead of `eth0`.
