### ISSUE TITLE
Unable to run Microsoft Edge Docker Image for WebdriverIo project

### ISSUE THREAD

**Issue by enliltom004** [aerokube/selenoid#1261]
Trying to connect to selenoid  MicrosoftEdge with docker image : browsers/edge:104.0 and it throws error : Unexpected token Y in JSON at position 0 in "http://127.0.0.1:4444/wb/hub/session"

```
[1-0] 2022-08-25T23:31:15.504Z ERROR webdriver: RequestError: Unexpected token Y in JSON at position 0 in "http://127.0.0.1:4444/session"
[1-0]     at Object.parseBody [as default] (/Users/tomen/Documents/wdio-docker-ci/node_modules/got/dist/source/as-promise/parse-body.js:22:15)
[1-0]     at Request.<anonymous> (/Users/tomen/Documents/wdio-docker-ci/node_modules/got/dist/source/as-promise/index.js:72:61)
[1-0]     at JSON.parse (<anonymous>)
[1-0]     at parseJson (/Users/tomen/Documents/wdio-docker-ci/node_modules/got/dist/source/index.js:118:35)
[1-0]     at Object.parseBody [as default] (/Users/tomen/Documents/wdio-docker-ci/node_modules/got/dist/source/as-promise/parse-body.js:11:48)
[1-0]     at Request.<anonymous> (/Users/tomen/Documents/wdio-docker-ci/node_modules/got/dist/source/as-promise/index.js:72:61)
```

I had the same issue with selenoid/firefox:103.0 but it was resolved after upgrading wdio to 7.22. But it is still not working for Edge .
My browser.json file 

```
"MicrosoftEdge": {
    "default": "latest",
    "versions": {
      "latest": {
        "image": "browsers/edge:104.0",
        "privileged": true,
        "port": "4444",
        "path": "/"
      }
    }
  },
```

WebdriverIo capability as follows
```
    {
      browserName: "MicrosoftEdge",
      path: "/",
      "ms:edgeOptions": {
        args: [
          "--headless",
          "--disable-dev-shm-usage",
          "--disable-infobars",
          "--no-sandbox",
          "--disable-gpu",
          "--remote-debugging-port=9902",
        ],
      },
      acceptInsecureCerts: true,
      "selenoid:options": {
        enableLog: true,
      },
    },
```

OS Configuration 
`macOS Monterey 12.5.1`

By hitting the endpoint http://127.0.0.1:4444/session getting this ,
```
You are using Selenoid 1.10.8!
^
```
Hence the json parsing error. 

I found a similar issue in [#1023 ](https://github.com/aerokube/selenoid/issues/1023) . 

Please note : If I pass "/wd/hub" in the capabilities the error will change to `[SESSION_FAILED] [http://192.168.112.6:4444/] [500 Internal Server Error]`

Can anyone help on this ?

**Comment by vania-pooh** [comment]
@enliltom004 should be `/session` instead of `/wd/hub/session` when using browser image directly. Otherwise path in `browsers.json` for non-Firefox images is always `/` but you go to Selenoid to `/wd/hub`.

**Comment by enliltom004** [comment]
Hi @vania-pooh , Thank you for your reply . I made a mistake in the question : the original error is 
`Unexpected token Y in JSON at position 0 in "http://127.0.0.1:4444/session"` and I the path set up in browsers.json is` "/"`

**Comment by vania-pooh** [comment]
@enliltom004 that means you are getting plain text message `You are using Selenoid 1.10.8!` (first letter is Y) instead of JSON.

**Comment by enliltom004** [comment]
Yes , As I mentioned in the question , it is getting the plain text message instead of Json . Not sure if it is a wdio issue as the same being discussed in #1023

**Comment by vania-pooh** [comment]
@enliltom004 if you are trying to start a browser session against Selenoid then base URL will always be `http://localhost:4444/wd/hub`. In `browsers.json` there is a `path` parameter that helps Selenoid to understand whether request to browser image should be sent to `/session` or `/wd/hub/session` respectively. You can omit this parameter at all and Selenoid will try both. Correct value for this parameter is `/wd/hub` for Firefox and `/` for all other browsers including Edge. Hope it helps.

**Comment by enliltom004** [comment]
Hi @vania-pooh , Thanks for your reply . I tried to connect to  Selenoid browser session with path parameter  set in browsers.json file . But it is failing for all browsers ( FF,Chrome , Edge ) with the same error `"Unexpected token Y in JSON at position 0 in `http://127.0.0.1:4444/session`. I tried with and without setting the path parameter , but same behaviour.

I tried to run the test against browser images and it worked for all browsers . In all the cases I had to set path `/wd/hub` in `wdio.conf.ts` file . But Chrome and Edge images had issues  in macOs with arm64, but it ran fine in linux machine .

note: `sskorol/selenoid_chromium_vnc:100.0` this image works for chrome in arm machine

**Comment by vania-pooh** [comment]
@enliltom004 for Selenoid URL should be `http://localhost:4444/wd/hub`. In your error message you have base Selenium URL set to `http://localhost:4444/`.
