### ISSUE TITLE
Session is not created for Android mobile test in WebdrverIO

### ISSUE THREAD

**Issue by HarryFree** [aerokube/selenoid#1271]
I am using mac M1 and creating docker build using alpine to run the android test.

dockerfile

```
FROM alpine:latest

RUN apk --no-cache add \
    build-base\
    python3\
    nodejs \
    npm \
    ffmpeg \
    libjpeg \
    cairo-dev \
    imagemagick \
    icu-dev \
    jpeg-dev \
    libpng-dev \
    pango-dev \
    giflib-dev \
    gd-dev \
    && npm install -g \
    npm@latest \
    android-tools \
    unzip \
    && rm -rf \
    /tmp/* \
    /root/.npm

RUN apk add --no-cache openjdk8
ENV JAVA_HOME=/usr/lib/jvm/default-jvm
ENV PATH="${JAVA_HOME}/bin:${PATH}"

# Download Android SDK and set PATH
RUN mkdir /android-sdk
RUN wget https://dl.google.com/android/repository/sdk-tools-linux-4333796.zip && unzip *.zip -d /android-sdk && rm *.zip
ENV ANDROID_HOME="/android-sdk"
ENV PATH="${PATH}:${ANDROID_HOME}/tools/bin"

# Install platform-tools
RUN yes | sdkmanager "platform-tools"
ENV PATH="${PATH}:${ANDROID_HOME}/platform-tools"
RUN apk --update-cache --repository http://dl-3.alpinelinux.org/alpine/edge/testing/ add android-tools
RUN adb version

WORKDIR /usr/lib/wdio

COPY package.json /usr/lib/wdio
COPY package-lock.json /usr/lib/wdio

RUN npm install \
    && rm -rf \
    /tmp/* \
    /root/.npm

COPY . /usr/lib/wdio

ENTRYPOINT [ "npm", "run" ]

#CMD [ "web-suite" ]

```

docker-compose 

```
version: "3.8"
services:
  selenoid:
    container_name: selenoid
    image: aerokube/selenoid:latest
    restart: unless-stopped
    network_mode: bridge
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/etc/selenoid/video/:/opt/selenoid/video/"
      - "/etc/selenoid/logs/:/opt/selenoid/logs/"
      - "/etc/selenoid/config/:/opt/selenoid/config/"
    environment:
      #- OVERRIDE_VIDEO_OUTPUT_DIR=$PWD
      - TZ=Asia/Singapore
    command:
      [
        "-conf",
        "/etc/selenoid/browsers.json",
        "-limit",
        "20",
        "-timeout",
        "20m",
        "-session-attempt-timeout",
        "2m",
        "-video-output-dir",
        "/etc/selenoid/video",
        "-log-output-dir",
        "/etc/selenoid/logs",
        "-save-all-logs"
      ]
    ports:
      - 4444:4444

  chrome:
    container_name: chrome
    image: sskorol/selenoid_chromium_vnc:100.0
    depends_on:
      - selenoid
    links:
      - selenoid
    volumes:
      - "/dev/shm:/dev/shm"
    ports:
      - 4446:4444

  android:
    container_name: android
    image: selenoid/android:10.0
    depends_on:
      - selenoid
    links:
      - selenoid
    volumes:
      - "/dev/shm:/dev/shm"
    ports:
      - 4447:4444

  selenoid-ui:
    container_name: selenoid-ui
    image: aerokube/selenoid-ui:latest-release
    restart: unless-stopped
    network_mode: bridge
    depends_on:
      - selenoid
    links:
      - selenoid
    ports:
      - 8080:8080
    command: [ "--selenoid-uri", "http://selenoid:4444" ]

```

browsers.json
```
{
    "chrome": {
        "default": "100.0",
        "versions": {
            "100.0": {
                "image": "sskorol/selenoid_chromium_vnc:100.0",
                "port": "4444",
                "path": "/",
                "env": [
                    "TZ=Asia/Singapore"
                ],
                "screen": "1920x1080x24",
                "volumes": []
            }
        }
    },
    "android": {
        "default": "10.0",
        "versions": {
            "10.0": {
                "image": "selenoid/android:10.0",
                "port": "4444",
                "path": "/",
                "env": [
                    "TZ=Asia/Singapore"
                ],
                "screen": "1920x1080x24",
                "volumes": []
            }
        }
    }
}
```

wdio config file

```
specs: [features()],
    specFileRetries: 0,
    specFileRetriesDelay: 5,
    capabilities: {
        browserName: 'android',
        platformName: 'Android',
        browserVersion: '10.0',
        'appium:platformVersion': '11',
        'appium:automationName': 'uiautomator2',
        'appium:connectHardwareKeyboard': false,
        'appium:newCommandTimeout': 240,
        'appium:orientation': 'PORTRAIT', //orient, // 'LANDSCAPE', // 'PORTRAIT'
        'appium:noReset': false,
        'appium:app': './resources/apps/app-release.apk',
        'selenoid:options':
        {
            'skin': 'WVGA854',
            'enableVNC': true,
            'enableVideo': false,
            'enableLog': true
        }
    },
    runner: 'local',
    protocol: 'http',
    hostname: 'selenoid',
    path: '/wd/hub',
    port: 4444,
    cucumberOpts: cucumberOptions(stepFiles, process.env.Tags)
```

When I run the test, It is not creating the session.

<img width="1415" alt="image" src="https://user-images.githubusercontent.com/107098655/195985988-4a7d6c96-cfbc-4ed7-9934-ac77abf2b52f.png">

error

```
2022-10-15T12:19:26.533Z ERROR @wdio/runner: Error: Failed to create session.
Timeout awaiting 'request' for 20000ms when running "http://selenoid:4444/wd/hub/session" with method "POST" and args "{"capabilities":{"alwaysMatch":{"browserName":"android","platformName":"Android","browserVersion":"10.0","appium:platformVersion":"11","appium:automationName":"uiautomator2","appium:connectHardwareKeyboard":false,"appium:newCommandTimeout":240,"appium:orientation":"PORTRAIT","appium:noReset":false,"appium:app":"./resources/apps/app-release.apk","selenoid:options":{"skin":"WVGA854","enableVNC":true,"enableVideo":false,"enableLog":true}},"firstMatch":[{}]},"desiredCapabilities":{"browserName":"android","platformName":"Android","browserVersion":"10.0","appium:platformVersion":"11","appium:automationName":"uiautomator2","appium:connectHardwareKeyboard":false,"appium:newCommandTimeout":240,"appium:orientation":"PORTRAIT","appium:noReset":false,"appium:app":"./resources/apps/app-release.apk","selenoid:options":{"skin":"WVGA854","enableVNC":true,"enableVideo":false,"enableLog":true}}}"
    at startWebDriverSession (/usr/lib/wdio/node_modules/webdriver/build/utils.js:73:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Function.newSession (/usr/lib/wdio/node_modules/webdriver/build/index.js:46:45)
    at async remote (/usr/lib/wdio/node_modules/webdriverio/build/index.js:77:22)
    at async Runner._startSession (/usr/lib/wdio/node_modules/@wdio/runner/build/index.js:223:56)
    at async Runner._initSession (/usr/lib/wdio/node_modules/@wdio/runner/build/index.js:176:25)
    at async Runner.run (/usr/lib/wdio/node_modules/@wdio/runner/build/index.js:88:19)
```

I saw this issue https://github.com/aerokube/selenoid/issues/1176 related but not sure they used docker image to run the test. I used Alpine docker image to run the test. 

(FYI: I also tried the same config on Linux machine, getting the same issue.) Please help on this issue

**Comment by vania-pooh** [comment]
@HarryFree running Android emulator requires `/dev/kvm` to be present. This is never the case under Mac (both AMD64 and ARM64). To run these images you need Linux hardware server.
