### ISSUE TITLE
after update: [SESSION_FAILED] [http://:4444/] [200 OK]

### ISSUE THREAD

**Issue by klaus7** [aerokube/selenoid#1326]
Hello everyone,

I already invested some hours into that, but I really can't figure this out. After upgrading to Selenoid 1.10.10 I immediatly receive a SESSION FAILED (with 200 OK... ) when trying to start a session.  

All I get from Selenium is a `Could not start a new session. Unable to parse remote response: You are using Selenoid 1.10.10!`

That leaves me rather clueless.

**Selenoid log:**
```
2023/03/22 13:08:07 [-] [INIT] [Loading configuration files...]
2023/03/22 13:08:07 [-] [INIT] [Loaded configuration from /etc/selenoid/browsers.json]
2023/03/22 13:08:07 [-] [INIT] [Video Dir: /opt/selenoid/video]
2023/03/22 13:08:07 [-] [INIT] [Logs Dir: /opt/selenoid/logs]
2023/03/22 13:08:07 [-] [INIT] [Using Docker API version: 1.12]
2023/03/22 13:08:07 [-] [INIT] [Timezone: UTC]
2023/03/22 13:08:07 [-] [INIT] [Listening on :4444]
2023/03/22 13:08:29 [-] [NEW_REQUEST] [unknown] [172.18.0.1]
2023/03/22 13:08:29 [-] [NEW_REQUEST_ACCEPTED] [unknown] [172.18.0.1]
2023/03/22 13:08:29 [0] [LOCATING_SERVICE] [chrome] []
2023/03/22 13:08:29 [-] [DEFAULT_VERSION] [Using default version: 111.0]
2023/03/22 13:08:29 [0] [USING_DOCKER] [chrome] [111.0]
2023/03/22 13:08:29 [0] [CREATING_CONTAINER] [selenoid/chrome:111.0]
2023/03/22 13:08:29 [0] [STARTING_CONTAINER] [selenoid/chrome:111.0] [58ac95a3c9e27f41c182fc729f643e304298596e4a0a57f9435cd4ba37d1548e]
2023/03/22 13:08:29 [0] [CONTAINER_STARTED] [selenoid/chrome:111.0] [58ac95a3c9e27f41c182fc729f643e304298596e4a0a57f9435cd4ba37d1548e] [0.38s]
2023/03/22 13:08:29 [0] [CREATING_VIDEO_CONTAINER] [selenoid/video-recorder:latest-release]
2023/03/22 13:08:29 [0] [STARTING_VIDEO_CONTAINER] [selenoid/video-recorder:latest-release] [71490031370f77e466dbfa407d7bbc2b806fd56d0ca1a82637b2d6934aa9b7de]
2023/03/22 13:08:30 [0] [VIDEO_CONTAINER_STARTED] [selenoid/video-recorder:latest-release] [71490031370f77e466dbfa407d7bbc2b806fd56d0ca1a82637b2d6934aa9b7de] [0.38s]
2023/03/22 13:08:30 [0] [SERVICE_STARTED] [selenoid/chrome:111.0] [58ac95a3c9e27f41c182fc729f643e304298596e4a0a57f9435cd4ba37d1548e] [0.00s]
2023/03/22 13:08:30 [0] [PROXY_TO] [58ac95a3c9e27f41c182fc729f643e304298596e4a0a57f9435cd4ba37d1548e] [http://:4444/]
2023/03/22 13:08:30 [0] [SESSION_ATTEMPTED] [http://:4444/] [1]
2023/03/22 13:08:30 [0] [SESSION_FAILED] [http://:4444/] [200 OK]
2023/03/22 13:08:30 [0] [STOPPING_VIDEO_CONTAINER] [71490031370f77e466dbfa407d7bbc2b806fd56d0ca1a82637b2d6934aa9b7de]
2023/03/22 13:09:00 [0] [REMOVING_CONTAINER] [71490031370f77e466dbfa407d7bbc2b806fd56d0ca1a82637b2d6934aa9b7de]
2023/03/22 13:09:00 [0] [CONTAINER_REMOVED] [71490031370f77e466dbfa407d7bbc2b806fd56d0ca1a82637b2d6934aa9b7de]
2023/03/22 13:09:00 [0] [REMOVING_CONTAINER] [58ac95a3c9e27f41c182fc729f643e304298596e4a0a57f9435cd4ba37d1548e]
2023/03/22 13:09:00 [0] [CONTAINER_REMOVED] [58ac95a3c9e27f41c182fc729f643e304298596e4a0a57f9435cd4ba37d1548e]
```

**Selenium (java) log:**
```
Could not start a new session. Unable to parse remote response: You are using Selenoid 1.10.10! 
Host info: host: 'myhost', ip: '127.0.1.1'
org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Unable to parse remote response: You are using Selenoid 1.10.10! 
Host info: host: 'myhost', ip: '127.0.1.1'
	at app//org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:134)
	at app//org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:106)
	at app//org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:67)
	at app//org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:156)
	at app//org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:543)
	at app//org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:229)
	at app//org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:157)
...
```

**Comment by klaus7** [comment]
@vania-pooh Thanks for your response, version should be fine. 

Output from `docker version`:
```
Client: Docker Engine - Community
 Cloud integration: v1.0.24
 Version:           23.0.1
 API version:       1.42
 Go version:        go1.19.5
 Git commit:        a5ee5b1
 Built:             Thu Feb  9 19:47:01 2023
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          23.0.1
  API version:      1.42 (minimum version 1.12)
  Go version:       go1.19.5
  Git commit:       bc3805a
  Built:            Thu Feb  9 19:47:01 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.18
  GitCommit:        2456e983eb9e37e47538f59ea18f2043c9a73640
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Comment by Vapross2712** [comment]
I have the same problem but  with a different error in response for starting session  ` {'status': 0, 'value': 'You are using Selenoid 1.10.7!'}`



**Selenoid log:**
`2023/03/23 15:37:26 [-] [NEW_REQUEST] [unknown] [34.76.65.254]
 2023/03/23 15:37:26 [-] [NEW_REQUEST_ACCEPTED] [unknown] [34.76.65.254]
 2023/03/23 15:37:26 [606] [LOCATING_SERVICE] [chrome] [111.0]
 2023/03/23 15:37:26 [606] [USING_DOCKER] [chrome] [111.0]
 2023/03/23 15:37:26 [606] [CREATING_CONTAINER] [selenoid/vnc_chrome:111.0]
 2023/03/23 15:37:26 [606] [STARTING_CONTAINER] [selenoid/vnc_chrome:111.0] [725133a519c59252d26507b614b3a4d11a813e3a81253020ab9593041efd42e6]
 2023/03/23 15:37:26 [606] [CONTAINER_STARTED] [selenoid/vnc_chrome:111.0] [725133a519c59252d26507b614b3a4d11a813e3a81253020ab9593041efd42e6] [0.37s]
 2023/03/23 15:37:26 [606] [SERVICE_STARTED] [selenoid/vnc_chrome:111.0] [725133a519c59252d26507b614b3a4d11a813e3a81253020ab9593041efd42e6] [0.00s]
 2023/03/23 15:37:26 [606] [PROXY_TO] [725133a519c59252d26507b614b3a4d11a813e3a81253020ab9593041efd42e6] [http://:4444/]
 2023/03/23 15:37:26 [606] [SESSION_ATTEMPTED] [http://:4444/] [1]
 2023/03/23 15:37:26 [606] [SESSION_FAILED] [http://:4444/] [200 OK]
 2023/03/23 15:37:26 [606] [REMOVING_CONTAINER] [725133a519c59252d26507b614b3a4d11a813e3a81253020ab9593041efd42e6]
 2023/03/23 15:37:26 [606] [CONTAINER_REMOVED] [725133a519c59252d26507b614b3a4d11a813e3a81253020ab9593041efd42e6]`



**docker version:**
`Client: Docker Engine - Community
 Version:           23.0.1
 API version:       1.42
 Go version:        go1.19.5
 Git commit:        a5ee5b1
 Built:             Thu Feb  9 19:46:56 2023
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          23.0.1
  API version:      1.42 (minimum version 1.12)
  Go version:       go1.19.5
  Git commit:       bc3805a
  Built:            Thu Feb  9 19:46:56 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.18
  GitCommit:        2456e983eb9e37e47538f59ea18f2043c9a73640
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
`

**Comment by vania-pooh** [comment]
@Vapross2712 tried with Ubuntu 22.04 and the same Docker version. Installed Selenoid with CM tool (`./cm selenoid start`).
```
root@ubuntu-s-1vcpu-1gb-fra1-01:~# docker logs -f selenoid
2023/03/26 15:44:40 [-] [INIT] [Loading configuration files...]
2023/03/26 15:44:40 [-] [INIT] [Loaded configuration from /etc/selenoid/browsers.json]
2023/03/26 15:44:40 [-] [INIT] [Video Dir: /opt/selenoid/video]
2023/03/26 15:44:40 [-] [INIT] [Logs Dir: /opt/selenoid/logs]
2023/03/26 15:44:40 [-] [INIT] [Using Docker API version: 1.42]
2023/03/26 15:44:40 [-] [INIT] [Timezone: UTC]
2023/03/26 15:44:40 [-] [INIT] [Listening on :4444]


2023/03/26 15:45:49 [-] [NEW_REQUEST] [unknown] [93.158.188.92]
2023/03/26 15:45:49 [-] [NEW_REQUEST_ACCEPTED] [unknown] [93.158.188.92]
2023/03/26 15:45:49 [5] [LOCATING_SERVICE] [chrome] [111.0]
2023/03/26 15:45:49 [5] [USING_DOCKER] [chrome] [111.0]
2023/03/26 15:45:49 [5] [CREATING_CONTAINER] [selenoid/chrome:111.0]
2023/03/26 15:45:49 [5] [STARTING_CONTAINER] [selenoid/chrome:111.0] [384fdad9e88109e945747a4562535cb65adbb3ea7b0b76a9ce79e0215fb70505]
2023/03/26 15:45:49 [5] [CONTAINER_STARTED] [selenoid/chrome:111.0] [384fdad9e88109e945747a4562535cb65adbb3ea7b0b76a9ce79e0215fb70505] [0.53s]
2023/03/26 15:45:51 [5] [SERVICE_STARTED] [selenoid/chrome:111.0] [384fdad9e88109e945747a4562535cb65adbb3ea7b0b76a9ce79e0215fb70505] [1.18s]
2023/03/26 15:45:51 [5] [PROXY_TO] [384fdad9e88109e945747a4562535cb65adbb3ea7b0b76a9ce79e0215fb70505] [http://172.18.0.4:4444/]
2023/03/26 15:45:51 [5] [SESSION_ATTEMPTED] [http://172.18.0.4:4444/] [1]
2023/03/26 15:45:53 [5] [SESSION_CREATED] [fede3e121d30d877e65dff6268d6e579] [1] [4.06s]
2023/03/26 15:45:53 [8] [CONTAINER_LOGS] [384fdad9e88109e945747a4562535cb65adbb3ea7b0b76a9ce79e0215fb70505]
2023/03/26 15:45:54 [9] [VNC_ENABLED] [fede3e121d30d877e65dff6268d6e579]
^C
root@ubuntu-s-1vcpu-1gb-fra1-01:~# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.2 LTS
Release:	22.04
Codename:	jammy
root@ubuntu-s-1vcpu-1gb-fra1-01:~# docker version
Client: Docker Engine - Community
 Version:           23.0.1
 API version:       1.42
 Go version:        go1.19.5
 Git commit:        a5ee5b1
 Built:             Thu Feb  9 19:47:01 2023
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          23.0.1
  API version:      1.42 (minimum version 1.12)
  Go version:       go1.19.5
  Git commit:       bc3805a
  Built:            Thu Feb  9 19:47:01 2023
  OS/Arch:          linux/amd64
  Experimental:     false

 containerd:
  Version:          1.6.19
  GitCommit:        1e1ea6e986c6c86565bc33d52e34b81b3e2bc71f
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

<img width="1280" alt="Screen Shot 2023-03-26 at 18 47 51" src="https://user-images.githubusercontent.com/829320/227787349-65f644ba-8934-4088-bae3-6ee1b2f10b45.png">
