### ISSUE TITLE
org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Response code 400. Message: invalid argument: entry 0 of 'firstMatch' is invalid

### ISSUE THREAD

**Issue by evalalos** [aerokube/selenoid#1356]
Hello,

I'm trying to start test on Edge browser -> browsers/edge:111.0 but I am getting the following error:

`org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Response code 400. Message: invalid argument: entry 0 of 'firstMatch' is invalid
from invalid argument: cannot parse capability: ms:edgeOptions
from invalid argument: unrecognized Microsoft Edge option: browserName
Build info: version: '4.1.1', revision: 'e8fcc2cecf'
System info: host: 'milos-2.local', ip: 'fe80:0:0:0:18eb:c54f:2ae8:41f5%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '13.4', java.version: '20.0.1'
Driver info: org.openqa.selenium.remote.RemoteWebDriver
Command: [null, newSession {capabilities=[Capabilities {browserName: MicrosoftEdge, browserVersion: 111.0, ms:edgeOptions: Capabilities {browserName: ..., selenoid:options: {enableVideo: false, env: [TZ=UTC], labels: {manual: true}, name: Selenium web test, sessionTimeout: 2m}}], desiredCapabilities=Capabilities {browserName: MicrosoftEdge, browserVersion: 111.0, ms:edgeOptions: Capabilities {browserName: ..., selenoid:options: {enableVideo: false, env: [TZ=UTC], labels: {manual: true}, name: Selenium web test, sessionTimeout: 2m}}}]
Capabilities {}

	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:126)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:84)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:62)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:156)
	at org.openqa.selenium.remote.TracedCommandExecutor.execute(TracedCommandExecutor.java:51)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:543)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:230)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:151)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:138)
	at common.WebDriverCreator.createDriver(WebDriverCreator.java:362)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.RunBefores.invokeMethod(RunBefores.java:33)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater$1.execute(IdeaTestRunner.java:38)
	at com.intellij.rt.execution.junit.TestsRepeater.repeat(TestsRepeater.java:11)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:35)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:232)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:55)`

My code for starting remote driver:

`case "MicrosoftEdge" -> {
                edgeOptions = new EdgeOptions();
                HashMap<String, Object> prefs = new HashMap<>();
                prefs.put("profile.default_content_settings.popups", 0);
                prefs.put("download.default_directory", this.downloadPath);
                prefs.put("download.prompt_for_download", false);
                prefs.put("download.directory_upgrade", true);
                edgeOptions.setExperimentalOption("prefs", prefs);
            }
            
            if (isRemote) {
            DesiredCapabilities capabilities = new DesiredCapabilities();
            capabilities.setCapability("browserVersion", selenoidBrowserVersion);
            capabilities.setCapability("selenoid:options", Map.of(
                    "name", "Selenium web test",
                    "sessionTimeout", "2m",
                    "env", List.of("TZ=UTC"),
                    "labels", Map.of("manual", "true"),
                    "enableVideo", false
            ));
            
            switch (browserName) {
                case "MicrosoftEdge" -> {
                    capabilities.setBrowserName("MicrosoftEdge");
                    capabilities.setCapability(EdgeOptions.CAPABILITY, edgeOptions);
                    this.driver = new RemoteWebDriver(new URL(SELENOID_HUB_URL), capabilities);
                }
                default -> throw new IllegalArgumentException("Invalid browser name provided.");
            }`
            
browsers.json on selenoid:

{
    "chrome": {
        "default": "113.0",
        "versions": {
            "112.0": {
                "image": "selenoid/chrome:112.0",
                "port": "4444",
                "path": "/"
            },
            "113.0": {
                "image": "selenoid/chrome:113.0",
                "port": "4444",
                "path": "/"
            }
        }
    },
    "firefox": {
        "default": "113.0",
        "versions": {
            "112.0": {
                "image": "selenoid/firefox:112.0",
                "port": "4444",
                "path": "/wd/hub"
            },
            "113.0": {
                "image": "selenoid/firefox:113.0",
                "port": "4444",
                "path": "/wd/hub"
            }
        }
    },
    "opera": {
        "default": "98.0",
        "versions": {
            "97.0": {
                "image": "selenoid/opera:97.0",
                "port": "4444",
                "path": "/"
            },
            "98.0": {
                "image": "selenoid/opera:98.0",
                "port": "4444",
                "path": "/"
            }
        }
    },
"MicrosoftEdge": {
        "default": "111.0",
        "versions": {
            "111.0": {
                "image": "browsers/edge:111.0",
                "port": "4444",
                "path": "/"
            }
        }
    }
}

This is the log from the selenoid server:

`2023/06/23 13:19:20 [-] [NEW_REQUEST] [unknown] [172.18.0.1]
2023/06/23 13:19:20 [-] [NEW_REQUEST_ACCEPTED] [unknown] [172.18.0.1]
2023/06/23 13:19:20 [3588] [LOCATING_SERVICE] [MicrosoftEdge] [111.0]
2023/06/23 13:19:20 [3588] [USING_DOCKER] [MicrosoftEdge] [111.0]
2023/06/23 13:19:20 [3588] [CREATING_CONTAINER] [browsers/edge:111.0]
2023/06/23 13:19:20 [3588] [STARTING_CONTAINER] [browsers/edge:111.0] [de94d5e347e69db52822008fbf545bb8de20a447dc9d87ec8bf07ec16de6e8e9]
2023/06/23 13:19:21 [3588] [CONTAINER_STARTED] [browsers/edge:111.0] [de94d5e347e69db52822008fbf545bb8de20a447dc9d87ec8bf07ec16de6e8e9] [0.25s]
2023/06/23 13:19:21 [3588] [SERVICE_STARTED] [browsers/edge:111.0] [de94d5e347e69db52822008fbf545bb8de20a447dc9d87ec8bf07ec16de6e8e9] [0.62s]
2023/06/23 13:19:21 [3588] [PROXY_TO] [de94d5e347e69db52822008fbf545bb8de20a447dc9d87ec8bf07ec16de6e8e9] [http://172.18.0.4:4444/]
2023/06/23 13:19:21 [3588] [SESSION_ATTEMPTED] [http://172.18.0.4:4444/] [1]
2023/06/23 13:19:21 [3588] [SESSION_FAILED] [http://172.18.0.4:4444/] [400 Bad Request]
2023/06/23 13:19:21 [3588] [REMOVING_CONTAINER] [de94d5e347e69db52822008fbf545bb8de20a447dc9d87ec8bf07ec16de6e8e9]
2023/06/23 13:19:21 [3588] [CONTAINER_REMOVED] [de94d5e347e69db52822008fbf545bb8de20a447dc9d87ec8bf07ec16de6e8e9]`

If you need anything else, please ask. 

Thanks in advance!

**Comment by vania-pooh** [comment]
@evalalos what is your Selenoid version? Recent Selenoid versions support `firstMatch` capability key.
