### ISSUE TITLE
Cannot start session on MacBook Pro with M3 Pro chip

### ISSUE THREAD

**Issue by evalalos** [aerokube/selenoid#1391]
Hello,
I'm unable to start a simple selenium test with my new MacBook Pro with M3 Pro chip. 

Same configuration/tests are running perfectly fine on the previous MacBook Pro with Intel chip. 

I'll paste the logs I have:

selenoid logs:

2024-01-02 16:51:03 2024/01/02 15:51:03 [-] [NEW_REQUEST] [unknown] [192.168.65.1]
2024-01-02 16:51:03 2024/01/02 15:51:03 [-] [NEW_REQUEST_ACCEPTED] [unknown] [192.168.65.1]
2024-01-02 16:51:03 2024/01/02 15:51:03 [313] [LOCATING_SERVICE] [firefox] [120.0]
2024-01-02 16:51:03 2024/01/02 15:51:03 [313] [USING_DOCKER] [firefox] [120.0]
2024-01-02 16:51:03 2024/01/02 15:51:03 [313] [CREATING_CONTAINER] [selenoid/firefox:120.0]
2024-01-02 16:51:03 2024/01/02 15:51:03 [313] [STARTING_CONTAINER] [selenoid/firefox:120.0] [4966ee07c6a3aa252ae52427885cfe8aa61a4073d84ebf7d14e1b7acdfa89b8e]
2024-01-02 16:51:03 2024/01/02 15:51:03 [313] [CONTAINER_STARTED] [selenoid/firefox:120.0] [4966ee07c6a3aa252ae52427885cfe8aa61a4073d84ebf7d14e1b7acdfa89b8e] [0.11s]
2024-01-02 16:51:03 2024/01/02 15:51:03 [313] [CREATING_VIDEO_CONTAINER] [selenoid/video-recorder:latest-release]
2024-01-02 16:51:03 2024/01/02 15:51:03 [313] [STARTING_VIDEO_CONTAINER] [selenoid/video-recorder:latest-release] [04eab5645df415049efb18ad902a883284be8c686cd8e03e0ecb59bd7e12cf32]
2024-01-02 16:51:03 2024/01/02 15:51:03 [313] [VIDEO_CONTAINER_STARTED] [selenoid/video-recorder:latest-release] [04eab5645df415049efb18ad902a883284be8c686cd8e03e0ecb59bd7e12cf32] [0.10s]
2024-01-02 16:51:33 2024/01/02 15:51:33 [313] [STOPPING_VIDEO_CONTAINER] [04eab5645df415049efb18ad902a883284be8c686cd8e03e0ecb59bd7e12cf32]
2024-01-02 16:51:34 2024/01/02 15:51:34 [313] [REMOVING_CONTAINER] [04eab5645df415049efb18ad902a883284be8c686cd8e03e0ecb59bd7e12cf32]
2024-01-02 16:51:34 2024/01/02 15:51:34 [313] [FAILED_TO_REMOVE_CONTAINER] [04eab5645df415049efb18ad902a883284be8c686cd8e03e0ecb59bd7e12cf32] [Error response from daemon: removal of container 04eab5645df415049efb18ad902a883284be8c686cd8e03e0ecb59bd7e12cf32 is already in progress]
2024-01-02 16:51:34 2024/01/02 15:51:34 [313] [REMOVING_CONTAINER] [4966ee07c6a3aa252ae52427885cfe8aa61a4073d84ebf7d14e1b7acdfa89b8e]
2024-01-02 16:51:34 2024/01/02 15:51:34 [313] [CONTAINER_REMOVED] [4966ee07c6a3aa252ae52427885cfe8aa61a4073d84ebf7d14e1b7acdfa89b8e]
2024-01-02 16:51:34 2024/01/02 15:51:34 [313] [SERVICE_STARTUP_FAILED] [wait: http://172.18.0.4:4444/wd/hub does not respond in 30s]

selenium+java logs:

org.openqa.selenium.SessionNotCreatedException: wait: http://172.18.0.4:4444/wd/hub does not respond in 30s
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'MacBook-Pro.local', ip: 'fe80:0:0:0:f2:6ae5:fd6a:fdb%en0', os.name: 'Mac OS X', os.arch: 'aarch64', os.version: '14.2.1', java.version: '19.0.2'
Driver info: driver.version: RemoteWebDriver
remote stacktrace: 

	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:67)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:484)
	at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$errorHandler$0(W3CHandshakeResponse.java:62)
	at org.openqa.selenium.remote.HandshakeResponse.lambda$getResponseFunction$0(HandshakeResponse.java:30)
	at org.openqa.selenium.remote.ProtocolHandshake.lambda$createSession$0(ProtocolHandshake.java:126)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:1016)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:647)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:128)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:74)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:136)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:213)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:131)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:144)
	at ui.framework.common.WebDriverCreator.createDriver(WebDriverCreator.java:339)

I'm also unable to manually create a session using selenoid-ui. Same issue occurs. 

Please if you need more logs, let me know.

Thanks in advance,
Milos

**Comment by vania-pooh** [comment]
@evalalos we never tested with M3, but e.g. with M1 \ M2 Chrome does not work simply because our browser images are build for x86 architecture and M1\2\3 chips are ARM.

**Comment by evalalos** [comment]
Ok, thanks for the reply. Do you know if it works with any other browser, e.g. Firefox?

**Comment by vania-pooh** [comment]
@vania-pooh probably Firefox will work.

**Comment by Hakeemmidan** [comment]
I got it (`selenoid/chrome:74.0` specifically) to work with MacBook M3 the following way:

1
```
docker pull selenoid/chrome:74.0
```
2
```
docker run -d --name chrome_74 -p 4444:4444 -p 5900:5900 -e ENABLE_VNC=true selenoid/chrome:74.0
```
3
a. Open "Finder", and then "Go" (from top menu bar) -> "Connect to server..."
b. Input "vnc://localhost:5900" as the Server Address
c. Input "selenoid" as the password (default password)

Then it should hopefully connect.
