### ISSUE TITLE
Panic in timeout logic

### ISSUE THREAD

**Issue by vania-pooh** [aerokube/selenoid#165]
With 1.3.2 getting the following panic:
```
panic: close of closed channel

goroutine 6467273 [running]:
main.proxy.func1.3(0xc420221800)
	/home/travis/gopath/src/github.com/aerokube/selenoid/selenoid.go:286 +0x244
net/http/httputil.(*ReverseProxy).ServeHTTP(0xc420bddf70, 0x89a940, 0xc42036e9a0, 0xc420221600)
	/home/travis/.gimme/versions/go1.8.linux.amd64/src/net/http/httputil/reverseproxy.go:159 +0x1be
main.proxy.func1(0xc4202e3d40, 0x89a940, 0xc42036e9a0, 0xc420221600)
	/home/travis/gopath/src/github.com/aerokube/selenoid/selenoid.go:301 +0x117
created by main.proxy
	/home/travis/gopath/src/github.com/aerokube/selenoid/selenoid.go:302 +0x7f
```

**Comment by vania-pooh** [comment]
Additionally Docker containers are not stopped:
```
CONTAINER ID        IMAGE                     COMMAND                  CREATED             STATUS                   PORTS               NAMES
0b34b15fc9a3        selenoid/chrome:48.0      "/bin/sh -c /entry..."   4 hours ago         Up 4 hours               4444/tcp            fervent_pike
6d756285d65f        selenoid/chrome:48.0      "/bin/sh -c /entry..."   4 hours ago         Up 4 hours               4444/tcp            zen_stonebraker
bb80ddd76dc9        selenoid/chrome:48.0      "/bin/sh -c /entry..."   4 hours ago         Up 4 hours               4444/tcp            cocky_khorana
129dc1a0016d        selenoid/firefox:46.0     "/bin/sh -c /entry..."   4 hours ago         Up 4 hours               4444/tcp            priceless_liskov
3d97815da586        selenoid/firefox:46.0     "/bin/sh -c /entry..."   4 hours ago         Up 4 hours               4444/tcp            gallant_nobel
a76ec226e99d        selenoid/firefox:46.0     "/bin/sh -c /entry..."   4 hours ago         Up 4 hours               4444/tcp            eloquent_hugle
a74c94fcc0b0        selenoid/firefox:46.0     "/bin/sh -c /entry..."   4 hours ago         Up 4 hours               4444/tcp            dazzling_poincare
b38379385205        selenoid/firefox:46.0     "/bin/sh -c /entry..."   4 hours ago         Up 4 hours               4444/tcp            jolly_wiles
220aff967ef0        selenoid/firefox:46.0     "/bin/sh -c /entry..."   4 hours ago         Up 4 hours               4444/tcp            epic_minsky
4be029972a88        selenoid/firefox:46.0     "/bin/sh -c /entry..."   4 hours ago         Up 4 hours               4444/tcp            loving_borg
aa44e8ca3641        selenoid/firefox:46.0     "/bin/sh -c /entry..."   4 hours ago         Up 4 hours               4444/tcp            confident_gates
bc9e5025ac52        selenoid/firefox:46.0     "/bin/sh -c /entry..."   4 hours ago         Up 4 hours               4444/tcp            condescending_shockley
0db61bc77771        selenoid/firefox:46.0     "/bin/sh -c /entry..."   4 hours ago         Up 4 hours               4444/tcp            sharp_bohr
503d17e34c3c        selenoid/firefox:46.0     "/bin/sh -c /entry..."   4 hours ago         Up 4 hours               4444/tcp            clever_kalam
e3fc2726702d        selenoid/chrome:48.0      "/bin/sh -c /entry..."   4 hours ago         Up 4 hours               4444/tcp            determined_payne
e47bb141c610        selenoid/firefox:46.0     "/bin/sh -c /entry..."   4 hours ago         Up 4 hours               4444/tcp            loving_bassi
17e614533e98        selenoid/firefox:46.0     "/bin/sh -c /entry..."   4 hours ago         Up 4 hours               4444/tcp            goofy_murdock
```

**Comment by vania-pooh** [comment]
This is expected to be resolved in Golang 1.8.3. Need to build latest code with this version and test whether the issue is still reproducing.

**Comment by vania-pooh** [comment]
Moving out the issue from 1.3.5 milestone as this should not reproduce after using Golang 1.8.3.

**Comment by vania-pooh** [comment]
This should have been fixed in latest releases.
