### ISSUE TITLE
Hung Tests

### ISSUE THREAD

**Issue by ryan-levell-twc** [aerokube/selenoid#265]
I am running some tests to figure out the best `-limit` for my machines. I am using 8 core machines. I have played around with the recommend 1.5-2 per core. I then run with a single Selenoid hub. I am running ~200 in parallel. About ~~10%~~ 80% of the time, 1 to 10 of the 200 tests get hung, seemingly indefinitely.

I execute `docker ps` and can see the hung tests, but after 1 minute the docker containers are removed, but the tests never complete.
```
$ docker ps
CONTAINER ID        IMAGE                     COMMAND                  CREATED             STATUS              PORTS                    NAMES
bcddfbd02f12        aerokube/selenoid:1.3.9   "/usr/bin/selenoid..."   12 minutes ago      Up 12 minutes       0.0.0.0:4445->4444/tcp   selenoid
// there were 7 hung chrome containers but after 60 seconds they were removed
```

I keep a list of running tests and the list should eventually be empty, but this test has had no output for 15 minutes and 7 tests are still left and the process is still running:
```
// starts with Left: [1..200]
Left: [6, 14, 40, 89, 91, 103, 112, 132, 150]
Left: [6, 14, 40, 89, 91, 103, 112, 132]
Left: [6, 14, 40, 89, 91, 103, 112] <-- stuck with 7 tests
// should end with - Left: []
```

**Comment by vania-pooh** [comment]
On the 8 core machine the recommended number of browsers is something like `12 to 16`. You can also check that your Docker settings are efficient for Selenoid [here](http://aerokube.com/selenoid/latest/#_recommended_docker_settings).

**Comment by ryan-levell-twc** [comment]
I changed to `16`. The first 5 executions completed successfully. The 6th execution had the same hanging issue. I had 10 of 220 tests hang indefinitely.

10 hung tests:
```
CONTAINER ID        IMAGE                     COMMAND                  CREATED             STATUS              PORTS                    NAMES
e577563fdb3c        selenoid/chrome:62.0      "/bin/sh -c /entry..."   47 seconds ago      Up 46 seconds       4444/tcp                 modest_kowalevski
5d51ad80be62        selenoid/chrome:62.0      "/bin/sh -c /entry..."   47 seconds ago      Up 46 seconds       4444/tcp                 amazing_raman
270d36e9e8fb        selenoid/chrome:62.0      "/bin/sh -c /entry..."   50 seconds ago      Up 49 seconds       4444/tcp                 flamboyant_noether
2efe69665475        selenoid/chrome:62.0      "/bin/sh -c /entry..."   51 seconds ago      Up 49 seconds       4444/tcp                 xenodochial_noether
d6cd40c53399        selenoid/chrome:62.0      "/bin/sh -c /entry..."   52 seconds ago      Up 50 seconds       4444/tcp                 laughing_pare
fd47b3c1dcb9        selenoid/chrome:62.0      "/bin/sh -c /entry..."   52 seconds ago      Up 50 seconds       4444/tcp                 distracted_lewin
57875a5b17ea        selenoid/chrome:62.0      "/bin/sh -c /entry..."   52 seconds ago      Up 52 seconds       4444/tcp                 cocky_mestorf
87a5e40527dd        selenoid/chrome:62.0      "/bin/sh -c /entry..."   54 seconds ago      Up 53 seconds       4444/tcp                 dreamy_brattain
a8c336027e4c        selenoid/chrome:62.0      "/bin/sh -c /entry..."   55 seconds ago      Up 53 seconds       4444/tcp                 festive_poincare
d31b77458276        selenoid/chrome:62.0      "/bin/sh -c /entry..."   56 seconds ago      Up 55 seconds       4444/tcp                 heuristic_hopper
95afcfca4331        aerokube/selenoid:1.3.9   "/usr/bin/selenoid..."   About an hour ago   Up About an hour    0.0.0.0:4445->4444/tcp   selenoid
```

10 hung test containers are destroyed:
```
 CONTAINER ID        IMAGE                     COMMAND                  CREATED             STATUS              PORTS                    NAMES
95afcfca4331        aerokube/selenoid:1.3.9   "/usr/bin/selenoid..."   About an hour ago   Up About an hour    0.0.0.0:4445->4444/tcp   selenoid
```

Process never ends and 10 jobs are still in my list:
```
// Left [1..220] starts with tests #1-#220
Left: [21, 35, 90, 111, 119, 159, 171, 185, 195, 200, 219, 220]
Left: [21, 35, 90, 111, 119, 159, 171, 185, 195, 200, 220]
Left: [21, 35, 90, 111, 119, 159, 171, 185, 195, 200] <-- stuck tests
```

The test takes about 2-3 minutes to complete when successful. I have waited >15 minutes on these hung tests and it won't complete.

Note, in the first 5 successful runs, 2 of the tests did have a single test hang, but each time it returned successfully shortly after the container was destroyed. I feel like that was the same hang scenario, but for whatever reason when there is >1 hung test, it never completes.

What additional info should I view to debug this further?

**Comment by ryan-levell-twc** [comment]
I have verified that each of the hung tests are hung on driver initialization:
```
DesiredCapabilities caps = DesiredCapabilities.chrome();
WebDriver driver = new RemoteWebDriver(new URL("http://user:password@1.2.3.4:4445/wd/hub"), caps);		
```

**Comment by vania-pooh** [comment]
As I said in my previous comment - you should take a look at server system metrics. When you start too many containers your server becomes slow and this is visible in test execution results. Also wrong network settings as well as slow Docker storage driver such as `DeviceMapper` can dramatically slow down things.

**Comment by ryan-levell-twc** [comment]
What is/how to check `load average`?
Limit is 16 on 8 cores.
Memory is sufficient: 9/16gb free during execution.
I now updated docker0.
`top` command reveals no bottle neck in memory or cpu.

Still same issue: hung at driver initialization. This time 7/220 hung:
```
ubuntu@ip-172-31-2-35:~$ docker ps
CONTAINER ID        IMAGE                     COMMAND                  CREATED             STATUS              PORTS                    NAMES
a7cd1b1c845d        selenoid/chrome:62.0      "/bin/sh -c /entry..."   37 seconds ago      Up 35 seconds       4444/tcp                 compassionate_thompson
83b708286dfc        selenoid/chrome:62.0      "/bin/sh -c /entry..."   37 seconds ago      Up 35 seconds       4444/tcp                 mystifying_newton
89789fbf40d9        selenoid/chrome:62.0      "/bin/sh -c /entry..."   37 seconds ago      Up 35 seconds       4444/tcp                 hopeful_carson
7cd3b10cb40e        selenoid/chrome:62.0      "/bin/sh -c /entry..."   41 seconds ago      Up 38 seconds       4444/tcp                 adoring_brahmagupta
f18c31eae911        selenoid/chrome:62.0      "/bin/sh -c /entry..."   42 seconds ago      Up 39 seconds       4444/tcp                 lucid_ardinghelli
863cb5f48876        selenoid/chrome:62.0      "/bin/sh -c /entry..."   42 seconds ago      Up 40 seconds       4444/tcp                 wonderful_goldstine
2d83ed7b03c8        selenoid/chrome:62.0      "/bin/sh -c /entry..."   42 seconds ago      Up 41 seconds       4444/tcp                 angry_lamport
95afcfca4331        aerokube/selenoid:1.3.9   "/usr/bin/selenoid..."   5 hours ago         Up 5 hours          0.0.0.0:4445->4444/tcp   selenoid
ubuntu@ip-172-31-2-35:~$ docker ps
CONTAINER ID        IMAGE                     COMMAND                  CREATED             STATUS              PORTS                    NAMES
95afcfca4331        aerokube/selenoid:1.3.9   "/usr/bin/selenoid..."   5 hours ago         Up 5 hours          0.0.0.0:4445->4444/tcp   selenoid
```

UPDATE on [previous execution](https://github.com/aerokube/selenoid/issues/265#issuecomment-343188758): The hung tests do finally end after 1-2 hours with this error:
```
FAILED: test
org.openqa.selenium.remote.UnreachableBrowserException: Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.
Build info: version: '3.7.0', revision: '2321c73', time: '2017-11-02T22:22:35.584Z'
System info: host: '----', ip: '---%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.12.6', java.version: '1.8.0_131'
Driver info: driver.version: RemoteWebDriver
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:621)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:219)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:142)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:155)
	at Main.test(Main.java:36)
	at sun.reflect.GeneratedMethodAccessor42.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:75)
	at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:171)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:137)
	at org.apache.http.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:153)
	at org.apache.http.impl.io.SessionInputBufferImpl.readLine(SessionInputBufferImpl.java:282)
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:138)
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:56)
	at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:259)
	at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:163)
	at org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:165)
	at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:273)
	at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:125)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:272)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:111)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:72)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
	at org.openqa.selenium.remote.internal.ApacheHttpClient.fallBackExecute(ApacheHttpClient.java:138)
	at org.openqa.selenium.remote.internal.ApacheHttpClient.execute(ApacheHttpClient.java:86)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:101)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:73)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:142)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:600)
	... 18 more
```

**Comment by ryan-levell-twc** [comment]
I tried with `limit 12` and 4 hung:

```
ubuntu@ip:~$ docker ps
CONTAINER ID        IMAGE                     COMMAND                  CREATED              STATUS              PORTS                    NAMES
369559a1eb6b        selenoid/chrome:62.0      "/bin/sh -c /entry..."   55 seconds ago       Up 54 seconds       4444/tcp                 romantic_mayer
047188540f3b        selenoid/chrome:62.0      "/bin/sh -c /entry..."   56 seconds ago       Up 54 seconds       4444/tcp                 quizzical_tesla
21c6fe13cca0        selenoid/chrome:62.0      "/bin/sh -c /entry..."   59 seconds ago       Up 57 seconds       4444/tcp                 distracted_ramanujan
cc1d601507fb        selenoid/chrome:62.0      "/bin/sh -c /entry..."   About a minute ago   Up 59 seconds       4444/tcp                 xenodochial_lumiere
d6a13b9e9699        aerokube/selenoid:1.3.9   "/usr/bin/selenoid..."   2 minutes ago        Up 2 minutes        0.0.0.0:4445->4444/tcp   selenoid
ubuntu@ip:~$ docker ps
CONTAINER ID        IMAGE                     COMMAND                  CREATED             STATUS              PORTS                    NAMES
d6a13b9e9699        aerokube/selenoid:1.3.9   "/usr/bin/selenoid..."   3 minutes ago       Up 3 minutes        0.0.0.0:4445->4444/tcp   selenoid
```

**Comment by vania-pooh** [comment]
@ryan-levell-twc 1) to check load average just type:
```
$ cat /proc/loadavg
... or
$ uptime
```
2) Default session timeout is 1 minute. So when your tests hung, their containers will be deleted 1 minute after last command. Tests waiting for session during hours is very strange. Are you somehow customizing your Selenium client? Do you have anything (e.g. Nginx) between Selenoid and your test?

**Comment by vania-pooh** [comment]
Also please take a look at Selenoid logs. You should be seeing entries with `[SESSION_TIMED_OUT]`. Please send an extract of Selenoid log here.

**Comment by ryan-levell-twc** [comment]
Yes the container successfully shuts down at 1 minute as shown above. And now I believe TestNG has a default 1 hour timeout that is being triggered to end the test.

If not for that 1 hour timeout, I believe it would hang indefinitely on driver initialization.

**Comment by ryan-levell-twc** [comment]
Here are my 5 hubs load:
```
ubuntu@ip:~$ uptime
 13:44:36 up 1 day, 18:12,  1 user,  load average: 4.96, 1.03, 0.33
ubuntu@ip:~$ uptime
 13:45:03 up 1 day, 18:12,  1 user,  load average: 18.21, 4.43, 1.47
ubuntu@ip:~$ uptime
 13:45:07 up 1 day, 18:12,  1 user,  load average: 20.19, 5.07, 1.70
ubuntu@ip:~$ uptime
 13:46:19 up 1 day, 18:13,  1 user,  load average: 34.84, 12.76, 4.62
ubuntu@ip:~$ uptime
 13:46:38 up 1 day, 18:14,  1 user,  load average: 34.09, 14.01, 5.21
ubuntu@ip:~$ uptime
 13:47:18 up 1 day, 18:14,  1 user,  load average: 20.09, 13.10, 5.28
---
ubuntu@ip:~$ uptime
 13:44:41 up 1 day, 18:12,  1 user,  load average: 7.28, 1.63, 0.54
ubuntu@ip:~$ uptime
 13:45:01 up 1 day, 18:12,  1 user,  load average: 17.79, 4.33, 1.45
ubuntu@ip:~$ uptime
 13:45:09 up 1 day, 18:12,  1 user,  load average: 19.97, 5.24, 1.78
ubuntu@ip:~$ uptime
 13:46:17 up 1 day, 18:13,  1 user,  load average: 38.64, 13.50, 4.86
ubuntu@ip:~$ uptime
 13:46:41 up 1 day, 18:14,  1 user,  load average: 39.09, 15.69, 5.82
ubuntu@ip:~$ uptime
 13:47:15 up 1 day, 18:14,  1 user,  load average: 21.84, 13.97, 5.61
---
ubuntu@ip:~$ uptime
 13:44:44 up 1 day, 21:46,  1 user,  load average: 7.85, 1.69, 0.55
ubuntu@ip:~$ uptime
 13:44:59 up 1 day, 21:46,  1 user,  load average: 14.06, 3.36, 1.12
ubuntu@ip:~$ uptime
 13:45:12 up 1 day, 21:46,  1 user,  load average: 22.60, 5.88, 1.98
ubuntu@ip:~$ uptime
 13:46:15 up 1 day, 21:47,  1 user,  load average: 36.37, 12.84, 4.62
ubuntu@ip:~$ uptime
 13:46:43 up 1 day, 21:48,  1 user,  load average: 35.91, 15.01, 5.60
ubuntu@ip:~$ uptime
 13:47:14 up 1 day, 21:48,  1 user,  load average: 33.64, 16.75, 6.50
---
ubuntu@ip:~$ uptime
 13:44:46 up 1 day, 21:46,  1 user,  load average: 7.63, 1.74, 0.57
ubuntu@ip:~$ uptime
 13:44:56 up 1 day, 21:46,  1 user,  load average: 15.89, 3.73, 1.23
ubuntu@ip:~$ uptime
 13:45:14 up 1 day, 21:46,  1 user,  load average: 25.72, 6.69, 2.26
ubuntu@ip:~$ uptime
 13:46:13 up 1 day, 21:47,  1 user,  load average: 40.51, 13.92, 4.98
ubuntu@ip:~$ uptime
 13:46:45 up 1 day, 21:48,  1 user,  load average: 36.48, 16.11, 6.06
ubuntu@ip:~$ uptime
 13:47:11 up 1 day, 21:48,  1 user,  load average: 24.03, 14.82, 5.90
---
ubuntu@ip:~$ uptime
 13:44:48 up 1 day, 18:12,  1 user,  load average: 9.52, 2.16, 0.70
ubuntu@ip:~$ uptime
 13:44:54 up 1 day, 18:12,  1 user,  load average: 12.68, 2.93, 0.96
ubuntu@ip:~$ uptime
 13:45:16 up 1 day, 18:12,  1 user,  load average: 25.28, 6.71, 2.27
ubuntu@ip:~$ uptime
 13:46:11 up 1 day, 18:13,  1 user,  load average: 36.87, 12.90, 4.63
ubuntu@ip:~$ uptime
 13:46:48 up 1 day, 18:14,  1 user,  load average: 35.72, 15.55, 5.84
ubuntu@ip:~$ uptime
 13:47:09 up 1 day, 18:14,  1 user,  load average: 25.58, 14.54, 5.72
```

2/5 hubs had hung tests. The container is shutdown within 1 minute. But the `new RemoteWebDriver` call never returns control.

**Comment by ryan-levell-twc** [comment]
Similar to the table above, I have been running 75 tests concurrently and it has not hung yet. It seems when the parallel count of my side is too high then a few begin to hang:
| # Parallel Threads | Max Grid Containers | # Tests To Run | Hung? |
| --- | --- | --- | --- |
| 200 | 16 | 220 | often |
| 75 | 16 | 220 | not yet |

I also pointed the tests to a cloud service and they do not hang, even when running 200 in parallel.

**Comment by vania-pooh** [comment]
So far as I can see you have load average = `30-40` which is very big. At least 4-5 processes are waiting for CPU under the load. I think this is why you are getting hung containers. Do you have anything else except Selenoid on these VMs? I would try to decrease `-limit` or find which process is "burning" your CPUs.

**Comment by ryan-levell-twc** [comment]
Nope these are new AWS machines, `c5.2xlarge` (8 cores). The only thing running is Selenoid in docker. Tests also hung with [`-limit 12`](https://github.com/aerokube/selenoid/issues/265#issuecomment-343263149).

Like I mentioned, it seems to happen when I am sending way more tests than my grid supports. If I have 200 parallel threads in my test execution and only a single hub with a limit of 16, then that is when I am getting some hung tests. When I reduced my parallel threads to 75, no tests have hung so far.

So the easy fix is to reduce the threads on my side. But my guess is that when the number of tests coming into Selenoid becomes too large compared to the limit, some tests are lost somehow.

**Comment by vania-pooh** [comment]
@ryan-levell-twc Selenoid has queues. If total number of parallel session is equal to `-limit` then new requests will wait for slots to free. While waiting these new requests can timeout.

**Comment by ryan-levell-twc** [comment]
Ok that may be the cause. It times out in `new RemoteWebDriver`, but then unintentionally loses/destroys the reference and never issues a response?

**Comment by vania-pooh** [comment]
Normally when `new RemoteWebDriver()` times out - an exception is thrown and you should have broken test cases. So not sure why it just "hungs" in your case.

**Comment by ryan-levell-twc** [comment]
Thanks, your comment lead me in a different direction. I was working on other things at the time, but I believe my "1-2 hour" wait was likely exactly 3 hours. Because there is a known issue about this: https://github.com/seleniumhq/selenium-google-code-issue-archive/issues/3951. I now think that is the core issue.
