### ISSUE TITLE
Close of closed channel not fixed

### ISSUE THREAD

**Issue by vania-pooh** [aerokube/selenoid#308]
Selenoid `1.4.0`.
```
2017/12/11 16:35:16 [SESSION_DELETED] [d9a72e1631ff8af65d9f4ed478fc1ced]
panic: close of closed channel

goroutine 2451892 [running]:
main.proxy.func1.3(0xc421747400)
        /home/travis/gopath/src/github.com/aerokube/selenoid/selenoid.go:357 +0x188
net/http/httputil.(*ReverseProxy).ServeHTTP(0xc420081f70, 0x905f40, 0xc420774380, 0xc421747300)
        /home/travis/.gimme/versions/go1.9.2.linux.amd64/src/net/http/httputil/reverseproxy.go:169 +0x17c
main.proxy.func1(0xc4203819e0, 0x905f40, 0xc420774380, 0xc421747300)
        /home/travis/gopath/src/github.com/aerokube/selenoid/selenoid.go:381 +0x112
created by main.proxy
        /home/travis/gopath/src/github.com/aerokube/selenoid/selenoid.go:344 +0x7a
```

**Comment by vania-pooh** [comment]
Should be fixed in #318.
