### ISSUE TITLE
Panic in /log API

### ISSUE THREAD

**Issue by vania-pooh** [aerokube/selenoid#404]
```
2018/03/28 09:15:12 [6265] [VNC_CLIENT_DISCONNECTED] [ecc7b5e94188749d91fc9b5ce075f36c]
2018/03/28 09:15:12 [6265] [VNC_SESSION_CLOSED] [ecc7b5e94188749d91fc9b5ce075f36c]
2018/03/28 09:15:16 [6307] [VNC_ENABLED] [ecc7b5e94188749d91fc9b5ce075f36c]
2018/03/28 09:15:17 [6308] [CONTAINER_LOGS] [&{e9ba0b964dea203377cff5e71e58c9da203a07fa1d9c7946730059b34ce46dae 172.17.0.4}]
2018/03/28 09:15:17 http: panic serving 172.17.0.3:51118: runtime error: invalid memory address or nil pointer dereference
goroutine 56987 [running]:
net/http.(*conn).serve.func1(0xc4201f8be0)
        /home/travis/.gimme/versions/go1.9.4.linux.amd64/src/net/http/server.go:1697 +0xd0
panic(0x745420, 0x9865e0)
        /home/travis/.gimme/versions/go1.9.4.linux.amd64/src/runtime/panic.go:491 +0x283
github.com/aerokube/selenoid/vendor/github.com/docker/docker/client.(*Client).getAPIPath(0x0, 0xc4205fad20, 0x51, 0xc4201c7fb0, 0x7eff1beb5d90, 0x0)
        /home/travis/gopath/src/github.com/aerokube/selenoid/vendor/github.com/docker/docker/client/client.go:213 +0x55
github.com/aerokube/selenoid/vendor/github.com/docker/docker/client.(*Client).sendRequest(0x0, 0x95c7a0, 0xc420571180, 0x7b1138, 0x3, 0xc4205fad20, 0x51, 0xc4201c7fb0, 0x0, 0x0, ...)
        /home/travis/gopath/src/github.com/aerokube/selenoid/vendor/github.com/docker/docker/client/request.go:118 +0xa3
github.com/aerokube/selenoid/vendor/github.com/docker/docker/client.(*Client).get(0x0, 0x95c7a0, 0xc420571180, 0xc4205fad20, 0x51, 0xc4201c7fb0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/travis/gopath/src/github.com/aerokube/selenoid/vendor/github.com/docker/docker/client/request.go:37 +0x12d
github.com/aerokube/selenoid/vendor/github.com/docker/docker/client.(*Client).ContainerLogs(0x0, 0x95c7a0, 0xc420571180, 0xc4200f4080, 0x40, 0x101, 0x0, 0x0, 0x0, 0x0, ...)
        /home/travis/gopath/src/github.com/aerokube/selenoid/vendor/github.com/docker/docker/client/container_logs.go:75 +0x274
main.logs(0xc42032f950)
        /home/travis/gopath/src/github.com/aerokube/selenoid/selenoid.go:490 +0x392
github.com/aerokube/selenoid/vendor/golang.org/x/net/websocket.Server.serveWebSocket(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/travis/gopath/src/github.com/aerokube/selenoid/vendor/golang.org/x/net/websocket/server.go:89 +0x181
github.com/aerokube/selenoid/vendor/golang.org/x/net/websocket.Handler.ServeHTTP(0x7c9010, 0x95c1a0, 0xc420354d20, 0xc4203c5b00)
        /home/travis/gopath/src/github.com/aerokube/selenoid/vendor/golang.org/x/net/websocket/server.go:112 +0xb4
net/http.(*ServeMux).ServeHTTP(0xc4203522d0, 0x95c1a0, 0xc420354d20, 0xc4203c5b00)
        /home/travis/.gimme/versions/go1.9.4.linux.amd64/src/net/http/server.go:2254 +0x130
net/http.serverHandler.ServeHTTP(0xc420075860, 0x95c1a0, 0xc420354d20, 0xc4203c5b00)
        /home/travis/.gimme/versions/go1.9.4.linux.amd64/src/net/http/server.go:2619 +0xb4
net/http.(*conn).serve(0xc4201f8be0, 0x95c7a0, 0xc420571000)
        /home/travis/.gimme/versions/go1.9.4.linux.amd64/src/net/http/server.go:1801 +0x71d
created by net/http.(*Server).Serve
        /home/travis/.gimme/versions/go1.9.4.linux.amd64/src/net/http/server.go:2720 +0x288
```

**Comment by sunofsparda** [comment]
`docker version`
```
Client:
 Version:      17.09.1-ce
 API version:  1.32
 Go version:   go1.8.5
 Git commit:   19e2cf6
 Built:        Thu Dec  7 22:19:00 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.09.1-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.5
 Git commit:   19e2cf6
 Built:        Thu Dec  7 22:19:00 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

```
2018/03/28 09:28:15 [4660] [VNC_ENABLED] [98632366a439964000ab90c8dc150c6c]
2018/03/28 09:28:15 [4661] [CONTAINER_LOGS] [&{c78c4faafdbc99074954bb8b7e53cd6e4e4620caaf79a87a9732a3ad74063b47 172.17.0.4}]
2018/03/28 09:28:15 http: panic serving 172.17.0.3:51014: runtime error: invalid memory address or nil pointer dereference
goroutine 43421 [running]:
net/http.(*conn).serve.func1(0xc420089680)
	/home/travis/.gimme/versions/go1.9.4.linux.amd64/src/net/http/server.go:1697 +0xd0
panic(0x745420, 0x9865e0)
	/home/travis/.gimme/versions/go1.9.4.linux.amd64/src/runtime/panic.go:491 +0x283
github.com/aerokube/selenoid/vendor/github.com/docker/docker/client.(*Client).getAPIPath(0x0, 0xc4202ffe60, 0x51, 0xc4202ecf90, 0x7f7fbef85000, 0x0)
	/home/travis/gopath/src/github.com/aerokube/selenoid/vendor/github.com/docker/docker/client/client.go:213 +0x55
github.com/aerokube/selenoid/vendor/github.com/docker/docker/client.(*Client).sendRequest(0x0, 0x95c7a0, 0xc420011a40, 0x7b1138, 0x3, 0xc4202ffe60, 0x51, 0xc4202ecf90, 0x0, 0x0, ...)
	/home/travis/gopath/src/github.com/aerokube/selenoid/vendor/github.com/docker/docker/client/request.go:118 +0xa3
github.com/aerokube/selenoid/vendor/github.com/docker/docker/client.(*Client).get(0x0, 0x95c7a0, 0xc420011a40, 0xc4202ffe60, 0x51, 0xc4202ecf90, 0x0, 0x0, 0x0, 0x0, ...)
	/home/travis/gopath/src/github.com/aerokube/selenoid/vendor/github.com/docker/docker/client/request.go:37 +0x12d
github.com/aerokube/selenoid/vendor/github.com/docker/docker/client.(*Client).ContainerLogs(0x0, 0x95c7a0, 0xc420011a40, 0xc4200f4080, 0x40, 0x101, 0x0, 0x0, 0x0, 0x0, ...)
	/home/travis/gopath/src/github.com/aerokube/selenoid/vendor/github.com/docker/docker/client/container_logs.go:75 +0x274
main.logs(0xc4201c7050)
	/home/travis/gopath/src/github.com/aerokube/selenoid/selenoid.go:490 +0x392
github.com/aerokube/selenoid/vendor/golang.org/x/net/websocket.Server.serveWebSocket(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/travis/gopath/src/github.com/aerokube/selenoid/vendor/golang.org/x/net/websocket/server.go:89 +0x181
github.com/aerokube/selenoid/vendor/golang.org/x/net/websocket.Handler.ServeHTTP(0x7c9010, 0x95c1a0, 0xc4202e0a80, 0xc42049ba00)
	/home/travis/gopath/src/github.com/aerokube/selenoid/vendor/golang.org/x/net/websocket/server.go:112 +0xb4
net/http.(*ServeMux).ServeHTTP(0xc4202ecbd0, 0x95c1a0, 0xc4202e0a80, 0xc42049ba00)
	/home/travis/.gimme/versions/go1.9.4.linux.amd64/src/net/http/server.go:2254 +0x130
net/http.serverHandler.ServeHTTP(0xc4203240d0, 0x95c1a0, 0xc4202e0a80, 0xc42049ba00)
	/home/travis/.gimme/versions/go1.9.4.linux.amd64/src/net/http/server.go:2619 +0xb4
net/http.(*conn).serve(0xc420089680, 0x95c7a0, 0xc420011940)
	/home/travis/.gimme/versions/go1.9.4.linux.amd64/src/net/http/server.go:1801 +0x71d
created by net/http.(*Server).Serve
	/home/travis/.gimme/versions/go1.9.4.linux.amd64/src/net/http/server.go:2720 +0x288

```

**Comment by sherlock1982** [comment]
```
Client:
 Version:       18.03.0-ce
 API version:   1.37
 Go version:    go1.9.4
 Git commit:    0520e24
 Built: Wed Mar 21 23:10:06 2018
 OS/Arch:       linux/amd64
 Experimental:  false
 Orchestrator:  swarm

Server:
 Engine:
  Version:      18.03.0-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.4
  Git commit:   0520e24
  Built:        Wed Mar 21 23:08:35 2018
  OS/Arch:      linux/amd64
  Experimental: false

```

```
2018/03/28 09:51:38 [21256] [USING_DOCKER] [firefox] [57.0]
2018/03/28 09:51:38 [21256] [CREATING_CONTAINER] [selenoid/vnc:firefox_57.0]
2018/03/28 09:51:39 [21256] [STARTING_CONTAINER] [selenoid/vnc:firefox_57.0] [da6cb67c2c183ef59949191d723821ced693209df399f3db41c70b2c2a3a2a17]
2018/03/28 09:51:40 [21256] [CONTAINER_STARTED] [selenoid/vnc:firefox_57.0] [da6cb67c2c183ef59949191d723821ced693209df399f3db41c70b2c2a3a2a17] [0.95s]
2018/03/28 09:51:40 [21256] [CREATING_VIDEO_CONTAINER] [selenoid/video-recorder]
2018/03/28 09:51:40 [21256] [STARTING_VIDEO_CONTAINER] [selenoid/video-recorder] [6c85720c1dd464326ebcdd1b5d687d372a9d4b95570b23d11238aec65e32b6c2]
2018/03/28 09:51:42 [21256] [VIDEO_CONTAINER_STARTED] [selenoid/video-recorder] [6c85720c1dd464326ebcdd1b5d687d372a9d4b95570b23d11238aec65e32b6c2] [1.83s]
2018/03/28 09:51:42 [21256] [SERVICE_STARTED] [selenoid/vnc:firefox_57.0] [da6cb67c2c183ef59949191d723821ced693209df399f3db41c70b2c2a3a2a17] [0.00s]
2018/03/28 09:51:42 [21256] [PROXY_TO] [da6cb67c2c183ef59949191d723821ced693209df399f3db41c70b2c2a3a2a17] [http://172.17.0.7:4444/wd/hub]
2018/03/28 09:51:42 [21256] [SESSION_ATTEMPTED] [http://172.17.0.7:4444/wd/hub] [1]
2018/03/28 09:51:46 [21181] [SESSION_CREATED] [f47e03be-f33b-4e68-9083-2887d71d4eb8] [1] [11.53s]
2018/03/28 09:51:49 [21256] [SESSION_CREATED] [4d7fcee1-1274-43ae-bda4-b22a3ae45372] [1] [10.75s]
2018/03/28 09:51:54 [21609] [VNC_ENABLED] [4d7fcee1-1274-43ae-bda4-b22a3ae45372]
2018/03/28 09:51:54 [21611] [CONTAINER_LOGS] [&{da6cb67c2c183ef59949191d723821ced693209df399f3db41c70b2c2a3a2a17 172.17.0.7}]
2018/03/28 09:51:54 http: panic serving 172.17.0.1:52916: runtime error: invalid memory address or nil pointer dereference
goroutine 166901 [running]:
net/http.(*conn).serve.func1(0xc42014e780)
        /home/travis/.gimme/versions/go1.9.4.linux.amd64/src/net/http/server.go:1697 +0xd0
panic(0x745420, 0x9865e0)
        /home/travis/.gimme/versions/go1.9.4.linux.amd64/src/runtime/panic.go:491 +0x283
github.com/aerokube/selenoid/vendor/github.com/docker/docker/client.(*Client).getAPIPath(0x0, 0xc420060b40, 0x51, 0xc42042a330, 0x7f98fd0716c8, 0x0)
        /home/travis/gopath/src/github.com/aerokube/selenoid/vendor/github.com/docker/docker/client/client.go:213 +0x55
github.com/aerokube/selenoid/vendor/github.com/docker/docker/client.(*Client).sendRequest(0x0, 0x95c7a0, 0xc420282c40, 0x7b1138, 0x3, 0xc420060b40, 0x51, 0xc42042a330, 0x0, 0x0, ...)
        /home/travis/gopath/src/github.com/aerokube/selenoid/vendor/github.com/docker/docker/client/request.go:118 +0xa3
github.com/aerokube/selenoid/vendor/github.com/docker/docker/client.(*Client).get(0x0, 0x95c7a0, 0xc420282c40, 0xc420060b40, 0x51, 0xc42042a330, 0x0, 0x0, 0x0, 0x0, ...)
        /home/travis/gopath/src/github.com/aerokube/selenoid/vendor/github.com/docker/docker/client/request.go:37 +0x12d
github.com/aerokube/selenoid/vendor/github.com/docker/docker/client.(*Client).ContainerLogs(0x0, 0x95c7a0, 0xc420282c40, 0xc42034c580, 0x40, 0x101, 0x0, 0x0, 0x0, 0x0, ...)
        /home/travis/gopath/src/github.com/aerokube/selenoid/vendor/github.com/docker/docker/client/container_logs.go:75 +0x274
main.logs(0xc420303680)
        /home/travis/gopath/src/github.com/aerokube/selenoid/selenoid.go:490 +0x392
github.com/aerokube/selenoid/vendor/golang.org/x/net/websocket.Server.serveWebSocket(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/travis/gopath/src/github.com/aerokube/selenoid/vendor/golang.org/x/net/websocket/server.go:89 +0x181
github.com/aerokube/selenoid/vendor/golang.org/x/net/websocket.Handler.ServeHTTP(0x7c9010, 0x95c1a0, 0xc42037cd20, 0xc420199c00)
        /home/travis/gopath/src/github.com/aerokube/selenoid/vendor/golang.org/x/net/websocket/server.go:112 +0xb4
net/http.(*ServeMux).ServeHTTP(0xc420344060, 0x95c1a0, 0xc42037cd20, 0xc420199c00)
        /home/travis/.gimme/versions/go1.9.4.linux.amd64/src/net/http/server.go:2254 +0x130
net/http.serverHandler.ServeHTTP(0xc4203301a0, 0x95c1a0, 0xc42037cd20, 0xc420199c00)
        /home/travis/.gimme/versions/go1.9.4.linux.amd64/src/net/http/server.go:2619 +0xb4
net/http.(*conn).serve(0xc42014e780, 0x95c7a0, 0xc4202828c0)
        /home/travis/.gimme/versions/go1.9.4.linux.amd64/src/net/http/server.go:1801 +0x71d
created by net/http.(*Server).Serve
        /home/travis/.gimme/versions/go1.9.4.linux.amd64/src/net/http/server.go:2720 +0x288
2018/03/28 09:52:05 [21942] [SESSION_DELETED] [4d7fcee1-1274-43ae-bda4-b22a3ae45372]
2018/03/28 09:52:05 [21256] [STOPPING_VIDEO_CONTAINER] [6c85720c1dd464326ebcdd1b5d687d372a9d4b95570b23d11238aec65e32b6c2]
2018/03/28 09:52:05 [21256] [STOPPED_VIDEO_CONTAINER] [6c85720c1dd464326ebcdd1b5d687d372a9d4b95570b23d11238aec65e32b6c2]
2018/03/28 09:52:05 [21256] [REMOVING_CONTAINER] [da6cb67c2c183ef59949191d723821ced693209df399f3db41c70b2c2a3a2a17]
2018/03/28 09:52:05 [21609] [VNC_SESSION_CLOSED] [4d7fcee1-1274-43ae-bda4-b22a3ae45372]
2018/03/28 09:52:05 [21609] [VNC_CLIENT_DISCONNECTED] [4d7fcee1-1274-43ae-bda4-b22a3ae45372]

```

**Comment by sherlock1982** [comment]
This might be the cause but it looks like selenoid/video-recorder containers are not deleted anymore.

**Comment by vania-pooh** [comment]
@sherlock1982 I think that's a consequence of Selenoid crash.

**Comment by fipso** [comment]
Ubuntu 16.04 LTS

```
2018/03/29 14:42:25 [0] [SESSION_TIMED_OUT] [dce31043bc35d905a2df1021f0ead7cc]
2018/03/29 14:42:25 [3] [SESSION_DELETED] [dce31043bc35d905a2df1021f0ead7cc]
2018/03/29 14:42:25 [0] [REMOVING_CONTAINER] [d4bd0321116b311df87253386f224fb05b0bd704004e8eea77d95accb1c84807]
2018/03/29 14:42:25 [0] [CONTAINER_REMOVED] [d4bd0321116b311df87253386f224fb05b0bd704004e8eea77d95accb1c84807]
2018/03/29 14:42:32 [4] [CONTAINER_LOGS] [&{13b794903ae28639d50a90d5c61dd3d692d6c90fc369a364aa79880cb74cb321 172.17.0.5}]
2018/03/29 14:42:32 http: panic serving 172.17.0.3:44870: runtime error: invalid memory address or nil pointer dereference
goroutine 173 [running]:
net/http.(*conn).serve.func1(0xc42032e820)
        /home/travis/.gimme/versions/go1.9.4.linux.amd64/src/net/http/server.go:1697 +0xd0
panic(0x745420, 0x9865e0)
        /home/travis/.gimme/versions/go1.9.4.linux.amd64/src/runtime/panic.go:491 +0x283
github.com/aerokube/selenoid/vendor/github.com/docker/docker/client.(*Client).getAPIPath(0x0, 0xc420452720, 0x51, 0xc420415d70, 0x7f11be3216c8, 0x0)
        /home/travis/gopath/src/github.com/aerokube/selenoid/vendor/github.com/docker/docker/client/client.go:213 +0x55
github.com/aerokube/selenoid/vendor/github.com/docker/docker/client.(*Client).sendRequest(0x0, 0x95c7a0, 0xc42030d900, 0x7b1138, 0x3, 0xc420452720, 0x51, 0xc420415d70, 0x0, 0x0, ...)
        /home/travis/gopath/src/github.com/aerokube/selenoid/vendor/github.com/docker/docker/client/request.go:118 +0xa3
github.com/aerokube/selenoid/vendor/github.com/docker/docker/client.(*Client).get(0x0, 0x95c7a0, 0xc42030d900, 0xc420452720, 0x51, 0xc420415d70, 0x0, 0x0, 0x0, 0x0, ...)
        /home/travis/gopath/src/github.com/aerokube/selenoid/vendor/github.com/docker/docker/client/request.go:37 +0x12d
github.com/aerokube/selenoid/vendor/github.com/docker/docker/client.(*Client).ContainerLogs(0x0, 0x95c7a0, 0xc42030d900, 0xc420167300, 0x40, 0x101, 0x0, 0x0, 0x0, 0x0, ...)
        /home/travis/gopath/src/github.com/aerokube/selenoid/vendor/github.com/docker/docker/client/container_logs.go:75 +0x274
main.logs(0xc42031aab0)
        /home/travis/gopath/src/github.com/aerokube/selenoid/selenoid.go:490 +0x392
github.com/aerokube/selenoid/vendor/golang.org/x/net/websocket.Server.serveWebSocket(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/travis/gopath/src/github.com/aerokube/selenoid/vendor/golang.org/x/net/websocket/server.go:89 +0x181
github.com/aerokube/selenoid/vendor/golang.org/x/net/websocket.Handler.ServeHTTP(0x7c9010, 0x95c1a0, 0xc4204661c0, 0xc420397d00)
        /home/travis/gopath/src/github.com/aerokube/selenoid/vendor/golang.org/x/net/websocket/server.go:112 +0xb4
net/http.(*ServeMux).ServeHTTP(0xc4202d2090, 0x95c1a0, 0xc4204661c0, 0xc420397d00)
        /home/travis/.gimme/versions/go1.9.4.linux.amd64/src/net/http/server.go:2254 +0x130
net/http.serverHandler.ServeHTTP(0xc4202fe1a0, 0x95c1a0, 0xc4204661c0, 0xc420397d00)
        /home/travis/.gimme/versions/go1.9.4.linux.amd64/src/net/http/server.go:2619 +0xb4
net/http.(*conn).serve(0xc42032e820, 0x95c7a0, 0xc42030d880)
        /home/travis/.gimme/versions/go1.9.4.linux.amd64/src/net/http/server.go:1801 +0x71d
created by net/http.(*Server).Serve
        /home/travis/.gimme/versions/go1.9.4.linux.amd64/src/net/http/server.go:2720 +0x288

```

**Comment by vania-pooh** [comment]
Currently we think that's an issue in Docker client.

**Comment by vania-pooh** [comment]
Very interesting. Does not reproduce on my Mac, however reproducing with any images under Linux.
