### ISSUE TITLE
Uploading file functionality doesn't work for firefox container

### ISSUE THREAD

**Issue by IZaiarnyi** [aerokube/selenoid#505]
I'm using:
-  latest (3.13.1) C# selenium client library
-  latest (1.7.1) selenoid server
-  61.0 and 58.0 firefox docker images

```C#
 _fileInput.WaitForPresent().SendKeys(fullFilePath);


OpenQA.Selenium.WebDriverException : zip: not a valid zip file
   at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteWebElement.Execute(String commandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteWebElement.UploadFile(String localFile)
   at OpenQA.Selenium.Remote.RemoteWebElement.SendKeys(String text)
```

**Comment by vania-pooh** [comment]
@IZaiarnyi does it work e.g. with Firefox 47 image?

**Comment by IZaiarnyi** [comment]
@vania-pooh It doesn't work with Firefox 47 image as well

**Comment by vania-pooh** [comment]
@IZaiarnyi and this is very strange because Firefox 47 images are using Java Selenium server inside. Does it work with Selenium server?

**Comment by IZaiarnyi** [comment]
@vania-pooh I've just checked it on selenium server 3.13.0 and it works there.

**Comment by IZaiarnyi** [comment]
@vania-pooh FYI:  It's working with Firefox 47 image but not  with 61.0 and 58.0. My bad.

**Comment by vania-pooh** [comment]
@IZaiarnyi this is Selenoid issue then. Will investigate.

**Comment by steviecs** [comment]
Uploading file functionality broken in Firefox 66 image as well

**Comment by vania-pooh** [comment]
@steviecs any test example to reproduce it?
