### ISSUE TITLE
How to load Chrome extensions

### ISSUE THREAD

**Issue by migorte** [aerokube/selenoid#571]
Hi,

In order to run my test framework, I need to load a Chrome extension. 

```
ChromeOptions options = new ChromeOptions();
options.addArguments("--load-extension=${WORKSPACE}/src/main/resources/myextension");
```

Although it works locally, is never loaded on Selenoid. I guess the WebDriver is trying to get it from a docker container path instead from the executor.

How could I sort this out?

Thanks in advance.

**Comment by vania-pooh** [comment]
@migorte see http://chromedriver.chromium.org/extensions

**Comment by migorte** [comment]
Thanks for your answer @vania-pooh.
However, I was already following that, both packed and unpacked ways, but still not working.

```
Exception in thread "main" org.openqa.selenium.WebDriverException: New session attempts retry count exceeded (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 31.54 seconds
Build info: version: '3.11.0', revision: 'e59cfb3', time: '2018-03-11T20:26:55.152Z'
System info: host: 'ESZAR1N1135', ip: '10.108.11.37', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_171'
Driver info: driver.version: RemoteWebDriver
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:214)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:166)
	at org.openqa.selenium.remote.JsonWireProtocolResponse.lambda$new$0(JsonWireProtocolResponse.java:53)
	at org.openqa.selenium.remote.JsonWireProtocolResponse.lambda$getResponseFunction$2(JsonWireProtocolResponse.java:91)
	at org.openqa.selenium.remote.ProtocolHandshake.lambda$createSession$0(ProtocolHandshake.java:123)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958)
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:126)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:73)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:136)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:545)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:209)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:132)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:145)
	at com.adidas.salesforce.consumerservice.webdriver.SeleniumRunner.main(SeleniumRunner.java:18)
```

My complete code looks like:
```
        ChromeOptions options = new ChromeOptions();
        options.addArguments("load-extension=" + "/src/main/resources/credentials");
        DesiredCapabilities capabilities = new DesiredCapabilities();
        capabilities.setCapability(ChromeOptions.CAPABILITY, options);
        WebDriver driver = new RemoteWebDriver(new URL("http://selenoid:4444/wd/hub"), (capabilities));
```
I tried also using chrome.switches with the same result. The docker images that we are using are selenoid/vnc:chrome_68.0 and selenoid/vnc:chrome_69.0.

**Comment by vania-pooh** [comment]
@migorte I think you have to use `profile` capability so Selenium client sends your extension to remote host.

**Comment by migorte** [comment]
@vania-pooh I tried with the profile capability but the issue is the same, the RemoteWebDriver is looking for the profile in the remote host, not in the Selenium client.
So if my ChromeOptions looks like:

`        options.addArguments("user-data-dir=" + "C:\\Users\\username\\AppData\\Local\\Google\\Chrome\\User Data");`

in the RemoteWebDriver this will be reflected as 

`2018-10-19T11:19:50.492764386Z [1539947990.490][INFO]: Launching chrome: /usr/bin/google-chrome --disable-background-networking --disable-client-side-phishing-detection --disable-default-apps --disable-hang-monitor --disable-popup-blocking --disable-prompt-on-repost --disable-sync --disable-web-resources --enable-automation --enable-logging --force-fieldtrials=SiteIsolationExtensions/Control --ignore-certificate-errors --load-extension=C:\Users\username\IdeaProjects\selenium/src/main/resources/credentials**,/tmp/.org.chromium.Chromium.i5CoIa/internal --log-level=0 --metrics-recording-only --no-first-run --password-store=basic --remote-debugging-port=12341 --test-type=webdriver --use-mock-keychain --user-data-dir=/tmp/.org.chromium.Chromium.1uIvgW data:,`

**Comment by migorte** [comment]
@vania-pooh I tried with the profile capability but the issue is the same, the RemoteWebDriver is looking for the profile in the remote host, not in the Selenium client.
So if my ChromeOptions looks like:

` options.addArguments("user-data-dir=" + "C:\\Users\\username\\AppData\\Local\\Google\\Chrome\\User Data");`

As the ChromeOptions are the switches for the ChromeDriver execution in the remote host,  this will be reflected as 
`[INFO]: Launching chrome: /usr/bin/google-chrome --user-data-dir=C:\\Users\\username\\AppData\\Local\\Google\\Chrome\\User Data`

So again it won't work because it's going to fetch the profile (or the extension) in the remote host, while actually it's in the client.

**Comment by toleksyn** [comment]
This code worked for me:
``` 
ChromeOptions options = new ChromeOptions();
options.addExtensions(new File(getClass().getClassLoader().getResource("extension.crx").getFile()));
WebDriver driver = new RemoteWebDriver(new URL("http://selenoid:4444/wd/hub"), options);
driver.get("https://google.com");
```

**Comment by ostap-oleksyn** [comment]
This code worked for me:
```
ChromeOptions options = new ChromeOptions();
options.addExtensions(new File(getClass().getClassLoader().getResource("extension.crx").getFile()));
WebDriver driver = new RemoteWebDriver(new URL("http://selenoid:4444/wd/hub"), options);
driver.get("https://google.com");
```

**Comment by vania-pooh** [comment]
@ostap-oleksyn yep, that seems to be correct snipped. Extension is then encoded as base64 and inserted to HTTP request.
