### ISSUE TITLE
org.openqa.selenium.WebDriverException: http://127.0.0.1:34433/ does not respond in 30s (WARNING: The server did not provide any stacktrace information) Command duration or timeout: 30.28 seconds

### ISSUE THREAD

**Issue by ivonin85** [aerokube/selenoid#738]
```
org.openqa.selenium.WebDriverException: http://127.0.0.1:34433/ does not respond in 30s (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 30.28 seconds
```

Привет!
Что он ищет вообще на http://127.0.0.1:34433/ )))
Селиноид здесь http://35.177.161.141:8080/#/

У себя в idea прописал 
```
DesiredCapabilities capabilities = new DesiredCapabilities();
        capabilities.setBrowserName("chrome");
        capabilities.setVersion("latest");
        capabilities.setCapability("enableVNC", true);
        capabilities.setCapability("enableVideo", false);

        RemoteWebDriver driver = new RemoteWebDriver(URI.create("http://35.177.161.141:4444/wd/hub").toURL(), capabilities);
```
Ошибка целиком 
```
org.openqa.selenium.WebDriverException: http://127.0.0.1:34433/ does not respond in 30s (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 30.28 seconds
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'IZDAT25', ip: '10.2.0.179', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_211'
Driver info: driver.version: RemoteWebDriver

	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:214)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:166)
	at org.openqa.selenium.remote.JsonWireProtocolResponse.lambda$errorHandler$0(JsonWireProtocolResponse.java:54)
	at org.openqa.selenium.remote.HandshakeResponse.lambda$getResponseFunction$0(HandshakeResponse.java:30)
	at org.openqa.selenium.remote.ProtocolHandshake.lambda$createSession$0(ProtocolHandshake.java:126)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958)
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:128)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:74)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:136)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:213)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:131)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:144)
	at selenium.settings.WebDriverSettings.setUp(WebDriverSettings.java:26)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)

```

**Comment by vania-pooh** [comment]
@ivonin85 Selenoid работает в режиме с драйверами и поднимает драйвер на случайном порту (в данном случае 34433), а потом по какой-то причине у вас не стартует браузер. Мы рекомендуем работать с Docker-контейнерами.

**Comment by ivonin85** [comment]
Не хочет работать ни в какую ... 
Последовательность действий следующая:
1 . `curl -s https://aerokube.com/cm/bash | bash \
    && ./cm selenoid start --vnc --tmpfs 128`
2. `sudo wget https://github.com/aerokube/cm/releases/download/1.5.7/cm_linux_amd64`
3. `sudo chmod +x ./cm`
4. `sudo ./cm selenoid start --vnc`
и все порт занят 
`Failed to start: failed to start container: Error response from daemon: driver failed programming external connectivity on endpoint selenoid (a61ea718d5c36a3f28e843c45b3ac20ca1fc27263f5202e4e9dad0e99ece4a31): Error starting userland proxy: listen tcp 0.0.0.0:4444: bind: address already in use`
а если до установки selenoid запустить `sudo wget https://github.com/aerokube/cm/releases/download/1.5.7/cm_linux_amd64` то утилита не скачивается ((

**Comment by aandryashin** [comment]
Добавьте опцию --force:
./cm selenoid start --force

пн, 3 июн. 2019 г., 22:52 Sergey Ivonin <notifications@github.com>:

**Comment by ivonin85** [comment]
Теперь браузеры не видит )) java.lang.NullPointerException ... 
http://34.214.134.224:8080/#/capabilities/

**Comment by vania-pooh** [comment]
Selenium-клиента попробуйте обновить.

**Comment by ivonin85** [comment]
Где его искать этот клиент?

**Comment by ivonin85** [comment]
У меня еще один вопрос возник: если у меня драйвер стоит на http://35.177.161.141:8080/#/ (aws) почему он пытается его поднять на локалхосте? и ищет http://127.0.0.1:39481/

**Comment by aandryashin** [comment]
У вас неправильно сконфигурировалось селеноид из за того что не хватало
пермиссий на докер. Попробуйте просто все переустановить?

вт, 4 июн. 2019 г., 9:56 Sergey Ivonin <notifications@github.com>:

**Comment by onpbxtester** [comment]
У меня было что-то похожее, помогло:
`sudo ./cm selenoid update`

**Comment by ivonin85** [comment]
Кстати рекомендацию **onpbxtester**  вам бы включить в мануал ... Ни разу у меня не вставал selenoid нормально при установке ... После апдейта все норм начинало работать ...

**Comment by vania-pooh** [comment]
Тут вроде бы все порешали.
