### ISSUE TITLE
Web driver exception in Windows 10 

### ISSUE THREAD

**Issue by qatestingravi** [aerokube/selenoid#745]
Hi @vania-pooh, 
In my windows 10 basic machine I got below error messages

------------------------------------
Error message in power shell:
2019/06/15 12:48:37 [-] [NEW_REQUEST] [unknown] [127.0.0.1]
2019/06/15 12:48:37 [-] [NEW_REQUEST_ACCEPTED] [unknown] [127.0.0.1]
2019/06/15 12:48:37 [0] [LOCATING_SERVICE] [chrome] [75]
2019/06/15 12:48:37 [0] [ENVIRONMENT_NOT_AVAILABLE] [chrome] [75]

Error message in tesntg:
org.openqa.selenium.WebDriverException: Requested environment is not available (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 71 milliseconds
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'RAVILAPTOP', ip: '192.168.99.1', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_77'
Driver info: driver.version: RemoteWebDriver
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:214)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:166)
	at org.openqa.selenium.remote.JsonWireProtocolResponse.lambda$errorHandler$0(JsonWireProtocolResponse.java:54)
	at org.openqa.selenium.remote.HandshakeResponse.lambda$getResponseFunction$0(HandshakeResponse.java:30)
	at org.openqa.selenium.remote.ProtocolHandshake.lambda$createSession$0(ProtocolHandshake.java:126)
	at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
	at java.util.Spliterators$ArraySpliterator.tryAdvance(Unknown Source)
	at java.util.stream.ReferencePipeline.forEachWithCancel(Unknown Source)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(Unknown Source)
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.util.stream.FindOps$FindOp.evaluateSequential(Unknown Source)
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.util.stream.ReferencePipeline.findFirst(Unknown Source)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:128)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:74)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:136)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:213)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:131)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:144)
	at utilities.DriverManager.createChromeDriver(DriverManager.java:67)
	at utilities.DriverManager.getDriver(DriverManager.java:32)
	at common.BaseTest.initialization(BaseTest.java:143)
	at testscripts.hotels.SearchHotels5.f(SearchHotels5.java:23)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
	at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

----------------------------------------------------------

Note1: I have not downloaded any binaries/images in windows for any browsers. Let me know if it is required to download manually the binaries/browsers in windows. 
Let me know the How to download and use it.
Note2: I don't have installed docker in my machine as i want executed browsers in my windows 10. Is it required to install docker?
Can you please help ?

I have performed following steps and I got above error messages

Step 1:
PS F:\Selenium\Selenoid> ./cm_windows_amd64.exe selenoid start --vnc
> Docker is not supported - using binaries...
> Selenoid is already downloaded
> Selenoid is already configured
> Starting Selenoid...
> Successfully started Selenoid
PS F:\Selenium\Selenoid> INIT] [Loaded configuration from C:\Users\DELL\.aerokube\selenoid\browsers.json]
PS F:\Selenium\Selenoid> INIT] [Logs Dir: F:\c\Users\DELL\.aerokube\selenoid\logs]
PS F:\Selenium\Selenoid> INIT] [Timezone: Local]
PS F:\Selenium\Selenoid> INIT] [Listening on :4444]
PS F:\Selenium\Selenoid> INIT] [Failed to start: listen tcp :4444: socket: The requested service provider could not be l

Step 2:
PS F:\Selenium\Selenoid> C:\Users\DELL\.aerokube\selenoid\selenoid_windows_amd64.exe -conf C:\Users\DELL\.aerokube\selenoid\browsers.json -disable-docker
2019/06/15 12:40:04 [-] [INIT] [Loading configuration files...]
2019/06/15 12:40:04 [-] [INIT] [Loaded configuration from C:\Users\DELL\.aerokube\selenoid\browsers.json]
2019/06/15 12:40:04 [-] [INIT] [Timezone: Local]
2019/06/15 12:40:04 [-] [INIT] [Listening on :4444]

Step 3:
Browsers.json file
{
    "chrome": {
        "default": "75.0",
        "versions": {
            "74.0": {
                "image": "selenoid/vnc_chrome:74.0",
                "port": "4444",
                "path": "/"
            },
            "75.0": {
                "image": "selenoid/vnc_chrome:75.0",
                "port": "4444",
                "path": "/"
            }
        }
    },
    "firefox": {
        "default": "67.0",
        "versions": {
            "66.0": {
                "image": "selenoid/vnc_firefox:66.0",
                "port": "4444",
                "path": "/wd/hub"
            },
            "67.0": {
                "image": "selenoid/vnc_firefox:67.0",
                "port": "4444",
                "path": "/wd/hub"
            }
        }
    },
    "opera": {
        "default": "60.0",
        "versions": {
            "58.0": {
                "image": "selenoid/vnc_opera:58.0",
                "port": "4444",
                "path": "/"
            },
            "60.0": {
                "image": "selenoid/vnc_opera:60.0",
                "port": "4444",
                "path": "/"
            }
        }
    }
}

Step4:
create driver with below capabilities
DesiredCapabilities capabilities = new DesiredCapabilities();
        capabilities.setBrowserName("chrome");
        capabilities.setVersion("75.0");
        capabilities.setCapability("enableVNC", true);
        capabilities.setCapability("enableVideo", false);
driver = new RemoteWebDriver(URI.create(http://localhost:4444/wd/hub).toURL(), capabilities);

**Comment by vania-pooh** [comment]
@qatestingravi with the configuration file above you have to install Docker as you are configuring Selenoid to use Docker image `selenoid/vnc_chrome:75.0` for browser with name `chrome` and version `75.0`. In order to use Selenoid with driver binaries directly on your Windows machine you have to specify driver startup command in square brackets instead as shown here: https://aerokube.com/selenoid/latest/#_using_selenoid_without_docker Driver binaries should be downloaded manually to some directory.

**Comment by qatestingravi** [comment]
Thanks @vania-pooh, its working after downloading the binaries and changing the browsers.json file as per your suggestion. 

Closing the issue as it is working
