### ISSUE TITLE
Can't create a session on firefox 71.0

### ISSUE THREAD

**Issue by calvin-lmi** [aerokube/selenoid#851]
I am not able to create a session on Firefox. 
Selenoid 1.9.2 (Updated to 1.9.3 but have the same issue) with selenoid/vnc_firefox:71.0

I get the following exception:```Error message: org.openqa.selenium.WebDriverException: Unable to parse remote response: You are using Selenoid 1.9.3!```

and the following docker log for the selenoid container:
```2019/12/17 06:24:09 [0] [LOCATING_SERVICE] [firefox] []
2019/12/17 06:24:09 [-] [DEFAULT_VERSION] [Using default version: stable]
2019/12/17 06:24:09 [0] [USING_DOCKER] [firefox] [stable]
2019/12/17 06:24:09 [0] [CREATING_CONTAINER] [docker-release-local.getgotools.net/g2mqa/firefox:stable]
2019/12/17 06:24:09 [0] [STARTING_CONTAINER] [docker-release-local.getgotools.net/g2mqa/firefox:stable] [89223dbd111f9e12b1927f13450aea2a3bff720d03809b80a2b495cc2ef80a56]
2019/12/17 06:24:09 [0] [CONTAINER_STARTED] [docker-release-local.getgotools.net/g2mqa/firefox:stable] [89223dbd111f9e12b1927f13450aea2a3bff720d03809b80a2b495cc2ef80a56] [0.44s]
2019/12/17 06:24:09 [0] [CREATING_VIDEO_CONTAINER] [selenoid/video-recorder:latest-release]
2019/12/17 06:24:09 [0] [STARTING_VIDEO_CONTAINER] [selenoid/video-recorder:latest-release] [26adb63dd72351cb79331dab8369b1830e531a493baed444255ffa0931266e98]
2019/12/17 06:24:10 [0] [VIDEO_CONTAINER_STARTED] [selenoid/video-recorder:latest-release] [26adb63dd72351cb79331dab8369b1830e531a493baed444255ffa0931266e98] [0.65s]
2019/12/17 06:24:10 [0] [SERVICE_STARTED] [docker-release-local.getgotools.net/g2mqa/firefox:stable] [89223dbd111f9e12b1927f13450aea2a3bff720d03809b80a2b495cc2ef80a56] [0.00s]
2019/12/17 06:24:10 [0] [PROXY_TO] [89223dbd111f9e12b1927f13450aea2a3bff720d03809b80a2b495cc2ef80a56] [http://172.17.0.6:4444]
2019/12/17 06:24:10 [0] [SESSION_ATTEMPTED] [http://172.17.0.6:4444] [1]
2019/12/17 06:24:10 [0] [SESSION_FAILED] [http://172.17.0.6:4444] [200 OK]
2019/12/17 06:24:10 [0] [STOPPING_VIDEO_CONTAINER] [26adb63dd72351cb79331dab8369b1830e531a493baed444255ffa0931266e98]
2019/12/17 06:24:10 [0] [REMOVING_CONTAINER] [26adb63dd72351cb79331dab8369b1830e531a493baed444255ffa0931266e98]
2019/12/17 06:24:10 [0] [FAILED_TO_REMOVE_CONTAINER] [26adb63dd72351cb79331dab8369b1830e531a493baed444255ffa0931266e98] [Error response from daemon: removal of container 26adb63dd72351cb79331dab8369b1830e531a493baed444255ffa0931266e98 is already in progress]
```

I presume this has to do with the latest change that displays a welcome message. Since [SESSION_FAILED] returns a [200 OK] I guess the session was started successfully but returns the welcome message instead of a JSON that indicates that the session was created properly?
As a temporary workaround we are now using selenoid/vnc_firefox:70.0 again that does not cause any problems.

**Comment by vania-pooh** [comment]
@calvin-lmi should use `path: "/wd/hub"` in `browsers.json` for any Firefox images.

**Comment by calvin-lmi** [comment]
That resolved my issue. Thanks!

**Comment by sofit** [comment]
3 of 154 tests failed.

browser.json:
`{
  "firefox": {
    "default": "latest",
    "versions": {
      "latest": {
        "image": "selenoid/firefox",
        "port": "4444",
        "path": "/wd/hub",
        "tmpfs": {
          "/tmp": "size=512m"
        }
      }
    }
  },
  "chrome": {
    "default": "latest",
    "versions": {
      "latest": {
        "image": "selenoid/chrome",
        "port": "4444",
        "tmpfs": {
          "/tmp": "size=512m"
        }
      }
    }
  }
}`

selenoid logs:
`[02:15:10]W:     [Step 4/6] 2021/12/23 23:06:17 [141] [LOCATING_SERVICE] [firefox] []
[02:15:10]W:     [Step 4/6] 2021/12/23 23:06:17 [141] [USING_DOCKER] [firefox] [latest]
[02:15:10]W:     [Step 4/6] 2021/12/23 23:06:17 [141] [CREATING_CONTAINER] [selenoid/firefox]
[02:15:10]W:     [Step 4/6] 2021/12/23 23:06:19 [141] [STARTING_CONTAINER] [selenoid/firefox] [b23777d71abaf6b3ffaeee2a9a71d99fa07c0265da216b60abd97f70ff9b4994]
[02:15:10]W:     [Step 4/6] 2021/12/23 23:06:23 [141] [CONTAINER_STARTED] [selenoid/firefox] [b23777d71abaf6b3ffaeee2a9a71d99fa07c0265da216b60abd97f70ff9b4994] [3.58s]
[02:15:10]W:     [Step 4/6] 2021/12/23 23:06:24 [141] [SERVICE_STARTED] [selenoid/firefox] [b23777d71abaf6b3ffaeee2a9a71d99fa07c0265da216b60abd97f70ff9b4994] [1.32s]
[02:15:10]W:     [Step 4/6] 2021/12/23 23:06:24 [141] [PROXY_TO] [b23777d71abaf6b3ffaeee2a9a71d99fa07c0265da216b60abd97f70ff9b4994] [http://172.17.0.14:4444/wd/hub]
[02:15:10]W:     [Step 4/6] 2021/12/23 23:06:24 [141] [SESSION_ATTEMPTED] [http://172.17.0.14:4444/wd/hub] [1]
[02:15:10]W:     [Step 4/6] 2021/12/23 23:06:54 [141] [SESSION_ATTEMPT_TIMED_OUT] [30s]
[02:15:10]W:     [Step 4/6] 2021/12/23 23:06:54 [141] [SESSION_ATTEMPTED] [http://172.17.0.14:4444/wd/hub] [2]
[02:15:10]W:     [Step 4/6] 2021/12/23 23:06:54 [141] [SESSION_FAILED] [http://172.17.0.14:4444/wd/hub] [200 OK]
[02:15:10]W:     [Step 4/6] 2021/12/23 23:06:54 [141] [REMOVING_CONTAINER] [b23777d71abaf6b3ffaeee2a9a71d99fa07c0265da216b60abd97f70ff9b4994]
[02:15:10]W:     [Step 4/6] 2021/12/23 23:06:56 [141] [CONTAINER_REMOVED] [b23777d71abaf6b3ffaeee2a9a71d99fa07c0265da216b60abd97f70ff9b4994]`

one of session.log
`2021-12-23T23:06:23.056537985Z 20
2021-12-23T23:06:23.064394945Z Waiting X server...
2021-12-23T23:06:23.175805480Z Logging to: /dev/null
2021-12-23T23:06:23.187214464Z Waiting X server...
2021-12-23T23:06:23.425175638Z Waiting X server...
2021-12-23T23:06:23.533625336Z Waiting X server...
2021-12-23T23:06:23.650545476Z 
2021-12-23T23:06:23.650590750Z  --- x11vnc loop: 1 ---
2021-12-23T23:06:23.650595902Z 
2021-12-23T23:06:24.151535784Z  --- x11vnc loop: waiting for: 110
2021-12-23T23:06:24.151576104Z 
2021-12-23T23:06:24.196907771Z PORT=5900
2021-12-23T23:06:24.418147070Z 2021/12/23 23:06:24 [-] [INIT] [Loading configuration files...]
2021-12-23T23:06:24.426332953Z 2021/12/23 23:06:24 [-] [INIT] [Loaded configuration from /tmp/browsers.json]
2021-12-23T23:06:24.434760999Z 2021/12/23 23:06:24 [-] [INIT] [Timezone: UTC]
2021-12-23T23:06:24.434776793Z 2021/12/23 23:06:24 [-] [INIT] [Listening on :4444]
2021-12-23T23:06:24.468299323Z 2021/12/23 23:06:24 [-] [NEW_REQUEST] [unknown] [172.17.0.2]
2021-12-23T23:06:24.468324666Z 2021/12/23 23:06:24 [-] [NEW_REQUEST_ACCEPTED] [unknown] [172.17.0.2]
2021-12-23T23:06:24.468868821Z 2021/12/23 23:06:24 [0] [LOCATING_SERVICE] [firefox] []
2021-12-23T23:06:24.468881763Z 2021/12/23 23:06:24 [-] [DEFAULT_VERSION] [Using default version: 95.0]
2021-12-23T23:06:24.468886090Z 2021/12/23 23:06:24 [0] [USING_DRIVER] [firefox] [95.0]
2021-12-23T23:06:24.468890021Z 2021/12/23 23:06:24 [0] [ALLOCATING_PORT]
2021-12-23T23:06:24.469448088Z 2021/12/23 23:06:24 [0] [ALLOCATED_PORT] [39473]
2021-12-23T23:06:24.469460103Z 2021/12/23 23:06:24 [0] [STARTING_PROCESS] [[/usr/bin/geckodriver --port=39473]]
2021-12-23T23:06:24.627734046Z 1640300784627	geckodriver	INFO	Listening on 127.0.0.1:39473
2021-12-23T23:06:25.011686151Z 2021/12/23 23:06:25 [0] [PROCESS_STARTED] [113] [0.54s]
2021-12-23T23:06:25.011721922Z 2021/12/23 23:06:25 [0] [PROXY_TO] [http://127.0.0.1:39473]
2021-12-23T23:06:25.011822935Z 2021/12/23 23:06:25 [0] [SESSION_ATTEMPTED] [http://127.0.0.1:39473] [1]
2021-12-23T23:06:25.055601726Z 1640300785055	mozrunner::runner	INFO	Running command: "/usr/bin/firefox" "--marionette" "-foreground" "-no-remote" "-profile" "/tmp/rust_mozprofiledwwMDE"
2021-12-23T23:06:51.545878382Z [GFX1-]: glxtest: libpci missing
2021-12-23T23:06:51.545902032Z [GFX1-]: glxtest: libEGL missing
2021-12-23T23:06:54.033196290Z 1640300814032	Marionette	INFO	Marionette enabled
2021-12-23T23:06:54.468651250Z 2021/12/23 23:06:54 [0] [CLIENT_DISCONNECTED] [unknown] [172.17.0.2] [30.00s]
2021-12-23T23:06:54.468684895Z 2021/12/23 23:06:54 [0] [TERMINATING_PROCESS] [113]
2021-12-23T23:06:54.469577990Z 2021/12/23 23:06:54 [0] [TERMINATED_PROCESS] [113] [0.00s]`

app.log 
`	 [createUser[1: Capabilities {acceptInsecureCerts: true, browserName: firefox, enableLog: false, enableVNC: true, loggingPrefs: org.openqa.selenium.logging..., pageLoadStrategy: eager, sessionTimeout: 3m}]] org.openqa.selenium.WebDriverException: Unable to parse remote response: You are using Selenoid 1.10.7!
	at AdminUserIT.<init>(AdminUserIT.java:38)
Caused by: org.openqa.selenium.json.JsonException: 
Unable to determine type from: Y. Last 1 characters read: Y
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'agent72.asd.center.cg', ip: '10.10.31.72', os.name: 'Linux', os.arch: 'amd64', os.version: '4.9.0-16-amd64', java.version: '1.8.0_201'
Driver info: driver.version: RemoteWebDriver
	at AdminUserIT.<init>(AdminUserIT.java:38)`
