### ISSUE TITLE
WebDriverError: wait: http://172.17.0.50:4444/ does not respond in 30s

### ISSUE THREAD

**Issue by mnjagadeesh** [aerokube/selenoid#881]
Hi, Any idea what is happening here? how to debug and fix it?

WebDriverError: wait: http://172.17.0.50:4444/ does not respond in 30s
    at Object.checkLegacyResponse (/home/qaadmin/sel/workspace/jjjj6-sanity-member-rnd/jjjj.ngtests/node_modules/selenium-webdriver/lib/error.js:639:15)
    at parseHttpResponse (/home/qaadmin/sel/workspace/jjjj6-sanity-member-rnd/jjjj.ngtests/node_modules/selenium-webdriver/http/index.js:538:13)
    at client_.send.then.response (/home/qaadmin/sel/workspace/jjjj6-sanity-member-rnd/jjjj.ngtests/node_modules/selenium-webdriver/http/index.js:472:11)
    at ManagedPromise.invokeCallback_ (/home/qaadmin/sel/workspace/jjjj6-sanity-member-rnd/jjjj.ngtests/node_modules/selenium-webdriver/lib/promise.js:1379:14)
    at TaskQueue.execute_ (/home/qaadmin/sel/workspace/jjjj6-sanity-member-rnd/jjjj.ngtests/node_modules/selenium-webdriver/lib/promise.js:2913:14)
    at TaskQueue.executeNext_ (/home/qaadmin/sel/workspace/jjjj6-sanity-member-rnd/jjjj.ngtests/node_modules/selenium-webdriver/lib/promise.js:2896:21)
    at asyncRun (/home/qaadmin/sel/workspace/jjjj6-sanity-member-rnd/jjjj.ngtests/node_modules/selenium-webdriver/lib/promise.js:2820:25)
    at /home/qaadmin/sel/workspace/jjjj6-sanity-member-rnd/jjjj.ngtests/node_modules/selenium-webdriver/lib/promise.js:639:7
    at process._tickCallback (internal/process/next_tick.js:68:7)
From: Task: WebDriver.createSession()
    at Function.createSession (/home/qaadmin/sel/workspace/jjjj6-sanity-member-rnd/jjjj.ngtests/node_modules/selenium-webdriver/lib/webdriver.js:329:24)
    at Builder.build (/home/qaadmin/sel/workspace/jjjj6-sanity-member-rnd/jjjj.ngtests/node_modules/selenium-webdriver/builder.js:458:24)
    at Hosted.DriverProvider.getNewDriver (/home/qaadmin/sel/workspace/jjjj6-sanity-member-rnd/jjjj.ngtests/node_modules/protractor/built/driverProviders/driverProvider.js:37:33)
    at Runner.createBrowser (/home/qaadmin/sel/workspace/jjjj6-sanity-member-rnd/jjjj.ngtests/node_modules/protractor/built/runner.js:198:43)
    at ProtractorBrowser.browser_.forkNewDriverInstance (/home/qaadmin/sel/workspace/jjjj6-sanity-member-rnd/jjjj.ngtests/node_modules/protractor/built/runner.js:224:36)
    at ProtractorBrowser.browser_.restart (/home/qaadmin/sel/workspace/jjjj6-sanity-member-rnd/jjjj.ngtests/node_modules/protractor/built/runner.js:239:33)
    at restartBrowser (/home/qaadmin/sel/workspace/jjjj6-sanity-member-rnd/jjjj.ngtests/node_modules/XXXX.ngtests/library/jjjjTesting.js:425:10)
    at Object.exports.performPreSpecSteps (/home/qaadmin/sel/workspace/jjjj6-sanity-member-rnd/jjjj.ngtests/node_modules/XXXX.ngtests/library/jjjjTesting.js:380:3)
    at Object.<anonymous> (/home/qaadmin/sel/workspace/jjjj6-sanity-member-rnd/jjjj.ngtests/member/spec/mcvDocumentsTwoSanitySpec.js:70:21)
    at /home/qaadmin/sel/workspace/jjjj6-sanity-member-rnd/jjjj.ngtests/node_modules/jasminewd2/index.js:94:23
From: Task: Run it("Test1 : Test to validate that user should be able to add document from within the documents from more button") in control flow
    at Object.<anonymous> (/home/qaadmin/sel/workspace/jjjj6-sanity-member-rnd/jjjj.ngtests/node_modules/jasminewd2/index.js:79:14)
    at attemptAsync (/home/qaadmin/sel/workspace/jjjj6-sanity-member-rnd/jjjj.ngtests/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:1916:24)
    at QueueRunner.run (/home/qaadmin/sel/workspace/jjjj6-sanity-member-rnd/jjjj.ngtests/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:1871:9)
    at QueueRunner.execute (/home/qaadmin/sel/workspace/jjjj6-sanity-member-rnd/jjjj.ngtests/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:1859:10)
    at Spec.queueRunnerFactory (/home/qaadmin/sel/workspace/jjjj6-sanity-member-rnd/jjjj.ngtests/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:697:35)
    at Spec.execute (/home/qaadmin/sel/workspace/jjjj6-sanity-member-rnd/jjjj.ngtests/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:359:10)
    at Object.fn (/home/qaadmin/sel/workspace/jjjj6-sanity-member-rnd/jjjj.ngtests/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:2479:37)
    at attemptAsync (/home/qaadmin/sel/workspace/jjjj6-sanity-member-rnd/jjjj.ngtests/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:1916:24)
    at QueueRunner.run (/home/qaadmin/sel/workspace/jjjj6-sanity-member-rnd/jjjj.ngtests/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:1871:9)
    at QueueRunner.execute (/home/qaadmin/sel/workspace/jjjj6-sanity-member-rnd/jjjj.ngtests/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:1859:10)
From asynchronous test: 
Error
    at Suite.<anonymous> (/home/qaadmin/sel/workspace/jjjj6-sanity-member-rnd/jjjj.ngtests/member/spec/mcvDocumentsTwoSanitySpec.js:58:5)
    at addSpecsToSuite (/home/qaadmin/sel/workspace/jjjj6-sanity-member-rnd/jjjj.ngtests/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:833:25)
    at Env.describe (/home/qaadmin/sel/workspace/jjjj6-sanity-member-rnd/jjjj.ngtests/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:802:7)
    at describe (/home/qaadmin/sel/workspace/jjjj6-sanity-member-rnd/jjjj.ngtests/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:3375:18)
    at Object.<anonymous> (/home/qaadmin/sel/workspace/jjjj6-sanity-member-rnd/jjjj.ngtests/member/spec/mcvDocumentsTwoSanitySpec.js:39:1)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)

**Comment by vania-pooh** [comment]
@mnjagadeesh depends on browser and where you run it.

**Comment by mnjagadeesh** [comment]
@vania-pooh am using 
REPOSITORY                TAG
selenoid/chrome            80.0
aerokube/selenoid-ui     1.9.2
aerokube/selenoid         1.10.0

Centos 7 with 5.5.7-1.el7.elrepo.x86_64 kernel.

**Comment by vania-pooh** [comment]
@mnjagadeesh take a look at browser container logs while it is running. Could be e.g. caused by enabled SELinux.

**Comment by mnjagadeesh** [comment]
@vania-pooh have disabled selinux. will read through logs to findout if anything is interesting

**Comment by mnjagadeesh** [comment]
@vania-pooh nothing interesting is found in log. But 'WebDriverError: wait: http://172.17.0.50:4444/ does not respond in 30s' error doesn't appear for every run.

**Comment by vania-pooh** [comment]
@mnjagadeesh could you try to set the following sysctl parameter?
```
$ sysctl -w net.ipv6.neigh.default.retrans_time_ms=1000 && echo 'net.ipv6.neigh.default.retrans_time_ms=1000' > /etc/sysctl.d/60-ipv6-retrans-time.conf
```

**Comment by mnjagadeesh** [comment]
@vania-pooh with this setting I see many 'WebDriverError: wait: http://172.17.0.50:4444/ does not respond in 30s' errors. With firefox, I do not see much change.

**Comment by aandryashin** [comment]
Is that error occurred for all tests? Most probably selenoid is overloaded,
in that case try to decrease number of parallel running tests or increase
service-startup-timeout.

пт, 13 мар. 2020 г., 11:04 JM <notifications@github.com>:

**Comment by mnjagadeesh** [comment]
@aandryashin you are correct. it is bit overloaded. I have 32core with 64G. I tried running 48 instances. I do not see this error after running 25 parallel instances. Also increased service-startup-timeout to 30. Thank you @aandryashin @vania-pooh  for all your help.
