### ISSUE TITLE
Timed out receiving message from renderer: 300.000

### ISSUE THREAD

**Issue by godomainz** [aerokube/selenoid#901]
I'm getting this error when I'm running long test cases.

OS : Ubuntu 18.04
Docker Version:           19.03.8
Docker API version:       1.40
No Of Containers : 4
RAM : 30GB
Processor : i7 9700k

browsers.json

```
{
    "chrome": {
        "default": "81.0",
        "versions": {
            "81.0": {
                "image": "selenoid/vnc:chrome_81.0",
                "port": "4444",
                "path": "/",
                "shmSize" : 268435456
            },
            "80.0": {
                "image": "selenoid/vnc:chrome_80.0",
                "port": "4444",
                "path": "/",
                "shmSize" : 268435456
            },
            "79.0": {
                "image": "selenoid/vnc:chrome_79.0",
                "port": "4444",
                "path": "/",
                "shmSize" : 268435456
            }
        }
    }
}
```

```
 { TimeoutError: timeout: Timed out receiving message from renderer: 300.000
matchdciprotractor_1   |   (Session info: chrome=81.0.4044.92)
matchdciprotractor_1   |   (Driver info: chromedriver=81.0.4044.69 (6813546031a4bc83f717a2ef7cd4ac6ec1199132-refs/branch-heads/4044@{#776}),platform=Linux 5.3.0-46-generic x86_64)
matchdciprotractor_1   |     at Object.checkLegacyResponse (/protractor/node_modules/selenium-webdriver/lib/error.js:546:15)
matchdciprotractor_1   |     at parseHttpResponse (/protractor/node_modules/selenium-webdriver/lib/http.js:509:13)
matchdciprotractor_1   |     at doSend.then.response (/protractor/node_modules/selenium-webdriver/lib/http.js:441:30)
matchdciprotractor_1   |     at process._tickCallback (internal/process/next_tick.js:68:7)
matchdciprotractor_1   | From: Task: WebDriver.switchTo().defaultContent()
matchdciprotractor_1   |     at thenableWebDriverProxy.schedule (/protractor/node_modules/selenium-webdriver/lib/webdriver.js:807:17)
matchdciprotractor_1   |     at TargetLocator.defaultContent (/protractor/node_modules/selenium-webdriver/lib/webdriver.js:1798:25)
matchdciprotractor_1   |     at Function.<anonymous> (/protractor/src/elements/utils.ts:112:38)
matchdciprotractor_1   |     at step (/protractor/dist/src/elements/utils.js:44:23)
matchdciprotractor_1   |     at Object.next (/protractor/dist/src/elements/utils.js:25:53)
matchdciprotractor_1   |     at /protractor/dist/src/elements/utils.js:19:71
matchdciprotractor_1   |     at new Promise (<anonymous>)
matchdciprotractor_1   |     at __awaiter (/protractor/dist/src/elements/utils.js:15:12)
matchdciprotractor_1   |     at Function.Utils.doSwitch (/protractor/dist/src/elements/utils.js:179:16)
matchdciprotractor_1   |     at Function.<anonymous> (/protractor/src/elements/utils.ts:98:20) name: 'TimeoutError', remoteStacktrace: '' }
```

**Comment by vania-pooh** [comment]
@godomainz this issue could signal that your Chrome browser has crashed. This could be e.g. because of insufficient shared memory. Try to increase `shmSize` parameter (default value is `256 megabytes`) as shown here: https://aerokube.com/selenoid/latest/#_other_optional_fields.

**Comment by godomainz** [comment]
@vania-pooh if you can see my browsers.json i added "shmSize" : 268435456.
same value as in that doc you mentioned.
Is that in bytes ?

**Comment by vania-pooh** [comment]
@godomainz it is in bytes and this is the default value automatically added by Selenoid anyway. Try to use bigger value.

**Comment by godomainz** [comment]
@vania-pooh I increased shmSize to 1068435456 still gave me the same issue. had to restart browser in afterAll() method to complete every spec file

**Comment by vania-pooh** [comment]
@godomainz in that case browser could be just freezing for some reason. Could you please then take a look at system metrics of the machine where containers are running (CPU consumption, load average, memory consumption, iowait and so on)?

**Comment by godomainz** [comment]
@vania-pooh please see the attached
![docker](https://user-images.githubusercontent.com/34884192/80197536-9f929980-85d3-11ea-90e4-de4986b85b52.png)

**Comment by vania-pooh** [comment]
@godomainz yes, video recording is as usually consuming a lot of CPU.

**Comment by godomainz** [comment]
@vania-pooh thats fine. but why is it freezing ? and whats the solution ?

**Comment by vania-pooh** [comment]
@godomainz have no idea. I would use Selenoid UI to see what's happening in browsers.
