### ISSUE TITLE
Unable to connect chrome devtools via selenoid websocket exception occur (Failed connecting to ws server)

### ISSUE THREAD

**Issue by Manikandan-Zoho** [aerokube/selenoid#918]
// Init standard Selenium session
        DesiredCapabilities caps = new DesiredCapabilities();
        caps.setBrowserName("chrome");
        driver = new RemoteWebDriver(new URL("http://localhost:4444/wd/hub"), caps);

        // Init ChromeDevtools client
        WebSocketService webSocketService = WebSocketServiceImpl.create(new URI(String.format("ws://localhost:4444/devtools/%s/page", driver.getSessionId())));
        CommandInvocationHandler commandInvocationHandler = new CommandInvocationHandler();
        Map<Method, Object> commandsCache = new ConcurrentHashMap<>();
        devtools =
                ProxyUtils.createProxyFromAbstract(
                        ChromeDevToolsServiceImpl.class,
                        new Class[] {WebSocketService.class, ChromeDevToolsServiceConfiguration.class},
                        new Object[] {webSocketService, new ChromeDevToolsServiceConfiguration()},
                        (unused, method, args) ->
                                commandsCache.computeIfAbsent(
                                        method,
                                        key -> {
                                            Class<?> returnType = method.getReturnType();
                                            return ProxyUtils.createProxy(returnType, commandInvocationHandler);
                                        }));
        commandInvocationHandler.setChromeDevToolsService(devtools);

I have run the above code 
I get the code from this link -
https://github.com/aerokube/chrome-developer-tools-protocol-java-example/blob/master/src/test/java/com/aerokube/selenoid/ChromeDevtoolsTest.java

**Kindly help me to connect a chrome devtool via RemoteWebDriver in java**

Exception occurs while create a **webSocketService** , I don't know the WebSocket URL and port is correct or not. 

Exception is --->
[main] WARN com.github.kklisura.cdt.services.impl.WebSocketServiceImpl - Failed connecting to ws server ws://localhost:4444/devtools/e5c04a9562dd785f86348a8d138f1ae3/browser...
javax.websocket.DeploymentException: Handshake error.
	at org.glassfish.tyrus.client.ClientManager$3$1.run(ClientManager.java:679)
	at org.glassfish.tyrus.client.ClientManager$3.run(ClientManager.java:717)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.glassfish.tyrus.client.ClientManager$SameThreadExecutorService.execute(ClientManager.java:871)
	at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:112)
	at org.glassfish.tyrus.client.ClientManager.connectToServer(ClientManager.java:516)
	at org.glassfish.tyrus.client.ClientManager.connectToServer(ClientManager.java:378)
	at com.github.kklisura.cdt.services.impl.WebSocketServiceImpl.connect(WebSocketServiceImpl.java:98)
	at com.github.kklisura.cdt.services.impl.WebSocketServiceImpl.create(WebSocketServiceImpl.java:86)
	at test.ChromeDevtoolsTest.setUp(ChromeDevtoolsTest.java:94)
	at test.ChromeDevtoolsTest.main(ChromeDevtoolsTest.java:60)
Caused by: org.glassfish.tyrus.core.HandshakeException: Response code was not 101: 404.
	at org.glassfish.tyrus.client.TyrusClientEngine.processResponse(TyrusClientEngine.java:320)
	at org.glassfish.tyrus.container.grizzly.client.GrizzlyClientFilter.handleHandshake(GrizzlyClientFilter.java:346)
	at org.glassfish.tyrus.container.grizzly.client.GrizzlyClientFilter.handleRead(GrizzlyClientFilter.java:315)
	at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:119)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:284)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:201)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:133)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:112)
	at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:77)
	at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:526)
	at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:112)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:117)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:56)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:137)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:591)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:571)
	at java.lang.Thread.run(Thread.java:748)
Exception in thread "main" com.github.kklisura.cdt.services.exceptions.WebSocketServiceException: Failed connecting to ws server {}
	at com.github.kklisura.cdt.services.impl.WebSocketServiceImpl.connect(WebSocketServiceImpl.java:120)
	at com.github.kklisura.cdt.services.impl.WebSocketServiceImpl.create(WebSocketServiceImpl.java:86)
	at test.ChromeDevtoolsTest.setUp(ChromeDevtoolsTest.java:94)
	at test.ChromeDevtoolsTest.main(ChromeDevtoolsTest.java:60)

**Comment by vania-pooh** [comment]
@Manikandan-Zoho which Chrome image are you using with this code?

**Comment by Manikandan-Zoho** [comment]
Iam using **selenoid/vnc_chrome:81.0** image

**Comment by vania-pooh** [comment]
@Manikandan-Zoho are you running this image alone or with Selenoid?

**Comment by Manikandan-Zoho** [comment]
@vania-pooh  I run with selenoid in this image

**Comment by vania-pooh** [comment]
@Manikandan-Zoho ok, one more thing - what is your Selenoid version?

**Comment by Manikandan-Zoho** [comment]
@vania-pooh I have using latest selenoid version1.10.0

**Comment by vania-pooh** [comment]
@Manikandan-Zoho let me check then.

**Comment by Manikandan-Zoho** [comment]
Ok, thanks @vania-pooh you will check and let me know.

**Comment by Manikandan-Zoho** [comment]
Hi @vania-pooh I am using **cdt-java-client from group com.github.kklisura.cdt (version 2.1.0)** jar file for this

**Comment by vania-pooh** [comment]
@Manikandan-Zoho created a test VM on DigitalOcean using this Marketplace image: https://cloud.digitalocean.com/marketplace/5c9b94b53b7d241092cc6f78?i=bc9d37 Replaced `localhost` in test with machine IP address, ran `testTakeScreenshot()` - works like a charm.

**Comment by Manikandan-Zoho** [comment]
Thank you very much @vania-pooh after pulling **aerokube/selenoid:1.10.0** image working fine.

One more help @vania-pooh I need to get javascript and css code coverage and get the used code line number or convert an offset into the line number. and need to the used css style file name (css url)

**Comment by vania-pooh** [comment]
@Manikandan-Zoho I don't know exactly all CDP methods \ fields. I would advice to just take a look at protocol [docs](https://chromedevtools.github.io/devtools-protocol/) and try to find respective field. Client library being used in our example is generating method names using JSON definition from CDP repository, so it is easy to match method names to this doc.

**Comment by Manikandan-Zoho** [comment]
Ok, Thanks @vania-pooh 👍

**Comment by vania-pooh** [comment]
@Manikandan-Zoho I think your issue should be resolved now, right?

**Comment by Manikandan-Zoho** [comment]
Yes @vania-pooh

**Comment by link89** [comment]
Hi, this feature seems not work when used with the `-disable-docker` option.
