### ISSUE TITLE
session may be closed due to extra webdriver

### ISSUE THREAD

**Issue by loudDD** [aerokube/selenoid#975]
Logs:
org.openqa.selenium.NoSuchSessionException: invalid session id
                        Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
                        System info: host: 'iadlnzalum1.novalocal', ip: 'Unknown', os.name: 'Linux', os.arch: 'amd64', os.version: '3.10.0-862.9.1.el7.x86_64',
                        java.version: '1.8.0_241'
                        Driver info: org.openqa.selenium.remote.RemoteWebDriver
                        Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 84.0.4147.89, chrome: {chromedriverVersion:
                        84.0.4147.30 (48b3e868b4cc0..., userDataDir: /tmp/.com.google.Chrome.oH8DIK}, goog:chromeOptions: {debuggerAddress: localhost:36089},
                        javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: LINUX, platformName: LINUX,
                        proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000},
                        unhandledPromptBehavior: dismiss and notify, webauthn:virtualAuthenticators: true}
                        Session ID: 4ea59a30318ccf51771dcdcdee12d3b5
                        	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
                        	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
                        	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
                        	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
                        	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:187)
                        	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:122)
                        	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
                        	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
                        	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
                        	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:609)
                        	at org.openqa.selenium.remote.RemoteWebDriver$RemoteNavigation.refresh(RemoteWebDriver.java:865)
                        	at com.lenovo.automation.Nitrogen.Common.CommonD365.refreshD365(CommonD365.java:1575)
                        	at com.lenovo.automation.Nitrogen.Common.CommonD365.deleteProductCategory(CommonD365.java:1128)
                        	at com.lenovo.automation.Nitrogen.TestCase_NIT_INT_DCG_E2E02.Step08_Delete_Product_By_Category(TestCase_NIT_INT_DCG_E2E02.java:212)
                        	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
                        	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
                        	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                        	at java.lang.reflect.Method.invoke(Method.java:498)
                        	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
                        	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
                        	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
                        	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
                        	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
                        	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
                        	at org.testng.TestRunner.privateRun(TestRunner.java:756)
                        	at org.testng.TestRunner.run(TestRunner.java:610)
                        	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
                        	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
                        	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:421)
                        	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
                        	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
                        	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
                        	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
                        	at java.lang.Thread.run(Thread.java:748)
                     

when my test steps click an element and a new chrome window will be open, and when I try to close the extra window and switchTo the origin window , the case will be stopped because of invalid session id.

**Comment by vania-pooh** [comment]
@loudDD depends on how you are closing the window.
```
driver.quit() # This will completely close browser
driver.close() # This will close current window tab
```
I think this is an issue in your code.

**Comment by loudDD** [comment]
I do use driver.close() . and it works fine in windows

**Comment by loudDD** [comment]
driver.switchTo().window(newhandle);
driver.close();
driver.switchTo().window(oldHandle);

**Comment by vania-pooh** [comment]
@loudDD this message comes from Chromedriver then. Seems to be a chromedriver-specific bug.

**Comment by loudDD** [comment]
thx , i'll try use other version of chrome
