### ISSUE TITLE
Cannot run android web tests on selenoid

### ISSUE THREAD

**Issue by xMagiciaNx** [aerokube/selenoid#976]
After many tests and debug, I run my tests with this command on Java:

`mvn verify -Dwebdriver.driver=remote -Dwebdriver.remote.url="http://$remoteAddress:4444/wd/hub" -Dwebdriver.remote.driver=appium -Dserenity.driver.capabilities="browserName:android" -Dappium.browserName=android`

It seemd that the selenoid android starting succesfull but keep giving me this:

`error: no devices/emulators found`

My config for browsers.json is 
`{
    "android": {
        "default": "6.0",
        "versions": {
            "6.0": {
                "image": "selenoid/android:6.0",
                "port": "4444",
                "path": "/wd/hub"
            }
        }
    }
}`

Do you see any issue in my configs? What am i doing wrong ? :/

**Comment by vania-pooh** [comment]
Are you running this one hardware server or a VM with nested virtualization enabled?

**Comment by xMagiciaNx** [comment]
I am running it on a cloud web server machine. So I need to enable nested virtualization ?

**Comment by vania-pooh** [comment]
@xMagiciaNx correct.

**Comment by xMagiciaNx** [comment]
I can't understand the issue really....

Here is what the coommand looks like:
`mvn verify -Dwebdriver.driver=remote -Dwebdriver.remote.url="http://<ip>:4444/wd/hub" -Dwebdriver.remote.driver=appium -Dserenity.driver.capabilities="browserName:android" -Dappium.browserName=android
`

Here is what I get from my VM:
`2020/08/26 10:15:13 [-] [NEW_REQUEST] [unknown] [185.32.231.212]
2020/08/26 10:15:13 [-] [NEW_REQUEST_ACCEPTED] [unknown] [185.32.231.212]
2020/08/26 10:15:13 [628] [LOCATING_SERVICE] [android] []
2020/08/26 10:15:13 [-] [DEFAULT_VERSION] [Using default version: 6.0]
2020/08/26 10:15:13 [628] [USING_DOCKER] [android] [6.0]
2020/08/26 10:15:13 [628] [CREATING_CONTAINER] [selenoid/android:6.0]
2020/08/26 10:15:13 [628] [STARTING_CONTAINER] [selenoid/android:6.0] [8be47cd418f66d4693f9881a4c041c3cf90881e129e4ce1534283fac72c0d026]
2020/08/26 10:15:14 [628] [CONTAINER_STARTED] [selenoid/android:6.0] [8be47cd418f66d4693f9881a4c041c3cf90881e129e4ce1534283fac72c0d026] [0.46s]
2020/08/26 10:15:54 [628] [SERVICE_STARTED] [selenoid/android:6.0] [8be47cd418f66d4693f9881a4c041c3cf90881e129e4ce1534283fac72c0d026] [40.44s]
2020/08/26 10:15:54 [628] [PROXY_TO] [8be47cd418f66d4693f9881a4c041c3cf90881e129e4ce1534283fac72c0d026] [http://172.18.0.4:4444/wd/hub]
2020/08/26 10:15:54 [628] [SESSION_ATTEMPTED] [http://172.18.0.4:4444/wd/hub] [1]
2020/08/26 10:15:54 [628] [SESSION_FAILED] [http://172.18.0.4:4444/wd/hub] [500 Internal Server Error]
2020/08/26 10:15:54 [628] [REMOVING_CONTAINER] [8be47cd418f66d4693f9881a4c041c3cf90881e129e4ce1534283fac72c0d026]
2020/08/26 10:15:58 [628] [CONTAINER_REMOVED] [8be47cd418f66d4693f9881a4c041c3cf90881e129e4ce1534283fac72c0d026]
`

And the Java stacktrace:
`The desired capabilities must include either an app, appPackage or browserName`

The think is that I actually pass this parameter. I testing this for weeks and no solution found yet :(

**Comment by vania-pooh** [comment]
@xMagiciaNx try to use `deviceName = android` instead of `browserName = android`.

**Comment by xMagiciaNx** [comment]
Oh, wow now this it may lead somewhere, i get
`Original error: URI and package arguments are required`

Android actually is starting it seems, i get all the ADB logs.

**Comment by vania-pooh** [comment]
@xMagiciaNx should specify `app` capability with an URL to tested application APK.

**Comment by xMagiciaNx** [comment]
The only thing I need is a browser to test a web app. Why I should put APKs ?

**Comment by vania-pooh** [comment]
@xMagiciaNx these images `selenoid/android:6.0` are for application testing and don't have Chrome inside. For Chrome mobile use these ones: https://aerokube.com/selenoid/latest/#_chrome_mobile

**Comment by xMagiciaNx** [comment]
Ty for your support but the issues is still there.
ADB is starting normally but I still getting the following error:
`URI and package arguments are required`

My browsers.json:
`{
"chrome-mobile": {
        "default": "mobile-79.0",
        "versions": {
            "mobile-79.0": {
                "image": "selenoid/chrome-mobile:79.0",
                "port": "4444",
                "path": "/wd/hub"
            }
        }
    }
}
`
Running command: 
`mvn verify -Dwebdriver.driver=remote -Dwebdriver.remote.url="http://$remoteAddress:4444/wd/hub" -Dserenity.driver.capabilities="browserName:chrome-mobile"
`
Some of the error i get from ADB:
Error1:
`2020-08-26 18:34:52:014 - [debug] [W3C (2807d632)] Encountered internal error running command: Error: URI and package arguments are required
2020-08-26 18:34:52:014 - [debug] [W3C (2807d632)]     at ADB.startUri (/opt/node_modules/appium/node_modules/appium-adb/lib/tools/apk-utils.js:59:11)
2020-08-26 18:34:52:015 - [debug] [W3C (2807d632)]     at AndroidUiautomator2Driver.commands.setUrl (/opt/node_modules/appium/node_modules/appium-uiautomator2-driver/lib/commands/general.js:146:18)
2020-08-26 18:34:52:015 - [debug] [W3C (2807d632)]     at commandExecutor (/opt/node_modules/appium/node_modules/appium-base-driver/lib/basedriver/driver.js:330:9)
2020-08-26 18:34:52:016 - [debug] [W3C (2807d632)]     at /opt/node_modules/appium/node_modules/async-lock/lib/index.js:125:12
2020-08-26 18:34:52:016 - [debug] [W3C (2807d632)]     at AsyncLock._promiseTry (/opt/node_modules/appium/node_modules/async-lock/lib/index.js:249:31)
2020-08-26 18:34:52:017 - [debug] [W3C (2807d632)]     at exec (/opt/node_modules/appium/node_modules/async-lock/lib/index.js:124:9)
2020-08-26 18:34:52:017 - [debug] [W3C (2807d632)]     at AsyncLock.acquire (/opt/node_modules/appium/node_modules/async-lock/lib/index.js:140:3)
2020-08-26 18:34:52:017 - [debug] [W3C (2807d632)]     at AndroidUiautomator2Driver.executeCommand (/opt/node_modules/appium/node_modules/appium-base-driver/lib/basedriver/driver.js:343:39)
2020-08-26 18:34:52:018 - [debug] [W3C (2807d632)]     at AppiumDriver.executeCommand (/opt/node_modules/appium/lib/appium.js:510:36)
2020-08-26 18:34:52:018 - [debug] [W3C (2807d632)]     at process._tickCallback (internal/process/next_tick.js:68:7)
`

Error2:
`2020-08-26 18:34:52:376 - [debug] [W3C (2807d632)] Encountered internal error running command: NotImplementedError: Method is not implemented
2020-08-26 18:34:52:378 - [debug] [W3C (2807d632)]     at AndroidUiautomator2Driver.execute (/opt/node_modules/appium/node_modules/appium-android-driver/lib/commands/execute.js:14:11)
2020-08-26 18:34:52:378 - [debug] [W3C (2807d632)]     at commandExecutor (/opt/node_modules/appium/node_modules/appium-base-driver/lib/basedriver/driver.js:330:9)
2020-08-26 18:34:52:378 - [debug] [W3C (2807d632)]     at /opt/node_modules/appium/node_modules/async-lock/lib/index.js:125:12
2020-08-26 18:34:52:378 - [debug] [W3C (2807d632)]     at AsyncLock._promiseTry (/opt/node_modules/appium/node_modules/async-lock/lib/index.js:249:31)
2020-08-26 18:34:52:379 - [debug] [W3C (2807d632)]     at exec (/opt/node_modules/appium/node_modules/async-lock/lib/index.js:124:9)
2020-08-26 18:34:52:379 - [debug] [W3C (2807d632)]     at AsyncLock.acquire (/opt/node_modules/appium/node_modules/async-lock/lib/index.js:140:3)
2020-08-26 18:34:52:379 - [debug] [W3C (2807d632)]     at AndroidUiautomator2Driver.executeCommand (/opt/node_modules/appium/node_modules/appium-base-driver/lib/basedriver/driver.js:343:39)
2020-08-26 18:34:52:379 - [debug] [W3C (2807d632)]     at AppiumDriver.executeCommand (/opt/node_modules/appium/lib/appium.js:510:36)
2020-08-26 18:34:52:379 - [debug] [W3C (2807d632)]     at process._tickCallback (internal/process/next_tick.js:68:7)
`
This really drives me crazy. I almost search the whole WWW

**Comment by vania-pooh** [comment]
@xMagiciaNx `browserName` should be `chrome` and `version` can be anything, e.g. `mobile-79.0`.

**Comment by xMagiciaNx** [comment]
Nope, this not working again :/ .
Again it asks for URI and packageName.
Should i try different image ?

**Comment by vania-pooh** [comment]
@xMagiciaNx what's the reason of setting browser name two times? Removing this should help: `-Dserenity.driver.capabilities=\"browserName:android\"`
