### ISSUE TITLE
When I run tests using selenoid I get error

### ISSUE THREAD

**Issue by Artashes1996** [aerokube/selenoid#987]
****Hello aerokube team, When I try execute my tests on Selenoid I get error**
Selenoid-ui runs on this url "http://192.168.44.201:8080/#/capabilities/".  

![Selection_011](https://user-images.githubusercontent.com/26311334/92765361-58504e00-f3a6-11ea-9bd6-f67e47e73efa.png)

**This is my code****
public class WebDriverFactory {
    public static WebDriver createWebDriver() throws IOException, URISyntaxException {
        Properties prop = new Properties();
        InputStream input = new FileInputStream("src/test/resources/config.properties");
        prop.load(input);
        DesiredCapabilities capabilities = DesiredCapabilities.chrome();
        capabilities.setCapability("browserName", "chrome");
        capabilities.setCapability("browserVersion", "85.0");
        capabilities.setCapability("enableVNC", true);
        capabilities.setCapability("enableVideo", true);
        RemoteWebDriver driver = new RemoteWebDriver(new URI("http://192.168.44.201:4444/wd/hub").toURL(), capabilities);
        if (prop.getProperty("selenium.server.hub") == null) {
            if (System.getProperty("os.name").startsWith("Windows")) {
                System.setProperty("webdriver.chrome.driver", "src/test/resources/drivers/chromedriver.exe");
                Log.info("Using Chrome Windows driver.");
            } else {
                Log.info("Use Linux");
                System.setProperty("webdriver.chrome.driver", "src/test/resources/drivers/chromedriver");
                Log.info("Using Chrome Linux driver.");
            }
            driver = new ChromeDriver();
        }
        return driver;
    }
}

**This is error**

```org.openqa.selenium.WebDriverException: create container: Error response from daemon: No such image: selenoid/vnc_chrome:85.0 (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 101 milliseconds
Build info: version: '3.14.0', revision: 'aacccce0', time: '2018-08-02T20:19:58.91Z'
System info: host: 'apivatya0820', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '5.4.0-45-generic', java.version: '1.8.0_265'
Driver info: driver.version: RemoteWebDriver

	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:214)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:166)
	at org.openqa.selenium.remote.JsonWireProtocolResponse.lambda$new$0(JsonWireProtocolResponse.java:53)
	at org.openqa.selenium.remote.JsonWireProtocolResponse.lambda$getResponseFunction$2(JsonWireProtocolResponse.java:91)
	at org.openqa.selenium.remote.ProtocolHandshake.lambda$createSession$0(ProtocolHandshake.java:122)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958)
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:499)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:486)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:531)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:125)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:73)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:136)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:548)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:212)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:130)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:143)
	at helper.WebDriverFactory.createWebDriver(WebDriverFactory.java:32)
	at BaseTest.setup(BaseTest.java:24)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:458)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
	at org.testng.TestRunner.beforeRun(TestRunner.java:529)
	at org.testng.TestRunner.run(TestRunner.java:497)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)```


public class WebDriverFactory {

    public static WebDriver createWebDriver() throws IOException, URISyntaxException {
        Properties prop = new Properties();
        InputStream input = new FileInputStream("src/test/resources/config.properties");
        prop.load(input);
        DesiredCapabilities capabilities = DesiredCapabilities.chrome();
        capabilities.setCapability("browserName", "chrome");
        capabilities.setCapability("browserVersion", "85.0");
        capabilities.setCapability("enableVNC", true);
        capabilities.setCapability("enableVideo", true);
        RemoteWebDriver driver = new RemoteWebDriver(new URI("http://192.168.44.201:4444/wd/hub").toURL(), capabilities);
        if (prop.getProperty("selenium.server.hub") == null) {
            if (System.getProperty("os.name").startsWith("Windows")) {
                System.setProperty("webdriver.chrome.driver", "src/test/resources/drivers/chromedriver.exe");
                Log.info("Using Chrome Windows driver.");
            } else {
                Log.info("Use Linux");
                System.setProperty("webdriver.chrome.driver", "src/test/resources/drivers/chromedriver");
                Log.info("Using Chrome Linux driver.");
            }
            driver = new ChromeDriver();
        }
        return driver;
    }
}

**Comment by vania-pooh** [comment]
@Artashes1996 any error messages in Selenoid logs could help to diagnose.

**Comment by Artashes1996** [comment]
Hi Ivan Krutov,thanks for answering my question. Please provide me
dockercommand that I can see Selenoid logs.

**Comment by vania-pooh** [comment]
@Artashes1996 `docker logs selenoid`
